### ISSUE TITLE
Xcache for NginX-PHP-FPM

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#10]
Zend opcache is enabled by default for NginX-PHP-FPM
My application support Xcache only!
How to enable Xcache instead of Zend Opcache?

**Comment by AnoopAlias** [comment]
you can remove the opcache rpm using yum and install xcache rpm (assuming you did the php install with remi rpm) if available

yum --disableexcludes=all --enablerepo=remi search xcache

would show that

If no xcache rpm available .you will be able to compile xcache using pecl or from the tgz source using phpize ; configure;make;make install

**Comment by sergeng** [comment]
SUCCESS!
I did 
yum --disableexcludes=all --enablerepo=remi remove php56-php-opcache
yum --disableexcludes=all --enablerepo=remi install php56-php-xcache php56-xcache-admin

and then modify the settings
nano /opt/remi/php56/root/etc/php.d/40-xcache.ini

and then 
systemctl restart nginx
systemctl restart php56-php-fpm.service

ET VOILA!
Thank you very much sir!

**Comment by AnoopAlias** [comment]
You can just do
systemctl restart ndeploy_backends

instead of

systemctl restart php56-php-fpm.service

Thats better and the way to manage php-fpm in nDeploy

**Comment by sergeng** [comment]
noted
thx

**Comment by sergeng** [comment]
tried xcache admin page with this 3 method but still get blank page or error
Method.1
cd /home/cpanel_user/public_html
ln -s /opt/remi/php56/root/usr/share/xcache xcache

Error.1
Page Not Found

Method.2
cd /home/cpanel_user/public_html
cp -a /home/cpeasyapache/src/xcache/xcache-3/htdocs xcache-admin

Error.2
Page Not Found

Method.3
nano /etc/nginx/sites-enabled/cpanel_user.com.include
        ## Xcache status pages for Remi repository
location ~ ^/xcacheadmin/(.+\.php)$ {
        alias /opt/remi/php56/root/usr/share/xcache/$1;
        fastcgi_pass unix:/opt/remi/php56/root/var/run/netto.sock;
        include /etc/nginx/fastcgi_params;
        }
location ~ /xcacheadmin {
        alias /opt/remi/php56/root/usr/share/xcache/;
        try_files $uri $uri/ /index.php;
        }

Error.3
This webpage is not available
ERR_CONNECTION_CLOSED


Xcache Setting
nano /opt/remi/php56/root/etc/php.d/40-xcache.ini
[xcache.admin]
xcache.admin.enable_auth = On
xcache.admin.user = "adminuser"
xcache.admin.pass = "7d5b7a58ed93e32d8b4u1e73880e750d"
xcache.mmap_path =    "/tmp/xcache"
xcache.cacher =              On
xcache.stat   =              On
xcache.optimizer =           On
xcache.size  =               256M
xcache.shm_scheme =        "mmap"
xcache.coverager =           Off

No Error in /var/log/nginx/error.log or /var/log/messages

Any suggestions
