### ISSUE TITLE
Error 503 no PHP-FPM sockets for PROXY httpd

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#100]
This is a nDeploy Cluster setup
After manually sorted out memcached for nginx pagespeed
I get error 503 on all my transferred cpanel account;

[root@web-01 ~]# tail -f /usr/local/apache/logs/error_log                   
[Sat Sep 03 12:20:01.754083 2016] [proxy:error] [pid 5930:tid 140191339632384] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/fpmsockets/account1.sock (*) failed
[Sat Sep 03 12:20:01.754099 2016] [proxy_fcgi:error] [pid 5930:tid 140191339632384] [client 192.168.40.103:37604] AH01079: failed to make connection to backend: httpd-UDS

[root@web-01 ~]# du -sh /opt/fpmsockets/                  
0       /opt/fpmsockets/

**Comment by AnoopAlias** [comment]
nDeploy does not support apache_httpd+php-fpm in newer versions. I suspect you upgraded to a new release ?. You must use a SAPI supported by cPanel like CGI/SuPHP for apache .

**Comment by sergeng** [comment]
Installed thru EasyApache4;
ea-apache24
•ea-apache24-config
•ea-apache24-config-runtime
•ea-apache24-mod_asis
•ea-apache24-mod_bwlimited
•ea-apache24-mod_cache
•ea-apache24-mod_cache_disk
•ea-apache24-mod_cache_socache
•ea-apache24-mod_cgid
•ea-apache24-mod_deflate
•ea-apache24-mod_env
•ea-apache24-mod_expires
•ea-apache24-mod_file_cache
•ea-apache24-mod_headers
•ea-apache24-mod_ldap
•ea-apache24-mod_mime_magic
•ea-apache24-mod_mpm_event
•ea-apache24-mod_proxy
•ea-apache24-mod_proxy_ajp
•ea-apache24-mod_proxy_fcgi
•ea-apache24-mod_proxy_http
•ea-apache24-mod_remoteip
•ea-apache24-mod_security2
•ea-apache24-mod_socache_memcache
•ea-apache24-mod_ssl
•ea-apache24-mod_suexec
•ea-apache24-mod_unique_id
•ea-apache24-mod_version
•ea-apache24-tools

Which should I remove?
Which should I add?

**Comment by AnoopAlias** [comment]
You should revert to 2.0 version of nDeploy from https://rpm.piserve.com/

run

`/opt/nDeploy/scripts/apache_php-fpm_setup.sh disable`

and then upgrade to newer versions of nDeploy 

nDeploy support php-fpm usage with nginX only in 3.x version. If you need to use php-fpm with httpd.Follow https://confluence2.cpanel.net/display/CKB/Configure+PHP-FPM+with+User+Pools+for+EasyApache+4

**Comment by AnoopAlias** [comment]
Or you can simply download and execute the script https://raw.githubusercontent.com/AnoopAlias/nDeploy/oldcode/scripts/apache_php-fpm_setup.sh

with the disable flag

**Comment by sergeng** [comment]
Same ERROR!
removed
•ea-php56-php-fpm
 •ea-php70-php-fpm
installed
•ea-apache24-mod_suphp

in WHM>Software>Multi PHP Manager>PHP Handlers
switched ea-php56 to SuPHP
rebooted
yet getting same ERROR!

**Comment by AnoopAlias** [comment]
@sergeng - This has nothing to do with php-fpm package or installing or uninstalling package. 

If you dont have any custom httpd modification you can try

```
rm -f /var/cpanel/templates/apache2_4/*.local
/scripts/rebuildhttpdconf

```

**Comment by sergeng** [comment]
That did the trick!
/opt/nDeploy/scripts/apache_php-fpm_setup.sh disable

Thank you very much!
We are back in business!!
