### ISSUE TITLE
let's encrypt, ndeploy and AutoSSL 

### ISSUE THREAD

**Issue by justvanbloom** [AnoopAlias/nDeploy#104]
there is a little bug when let's encrypt plugin and autossl is installed.
the domains configured with php enabled (remi only - not ea) cant proper configure with autossl.

please add to nginx conf for php remi backends:

`location ~ /.well-known {
                allow all;
        }`

**Comment by AnoopAlias** [comment]
Can you let me know the exact template in use  . remi/ea does not affect the config (it just change the socket path). I believe all templates have .well-known allowed.

Let me know.

**Comment by AnoopAlias** [comment]
@justvanbloom - I am closing this for now ..feel free to reopen it anytime
