### ISSUE TITLE
HHVM Cluster

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#105]
http://ndeploy.readthedocs.io/en/latest/nDeploy_cluster_setup.html
10. Setup PHP-FPM backends (for PHP) and Phusion Passenger ( RUBY , PYTHON , NODEJS) on all servers in the cluster

Why not HHVM also?
What is the manually supported way to install HHVM as backend on slaves?

**Comment by AnoopAlias** [comment]
HHVM and ColdFusion work too(although not mentioned). You just need to follow

http://ndeploy.readthedocs.io/en/latest/HHVM.html on the master and slaves.
