### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH occuring

### ISSUE THREAD

**Issue by Teranode** [AnoopAlias/nDeploy#109]
When I installed ndeploy and started to use it, most of the emages started generating this error:

net::ERR_CONTENT_LENGTH_MISMATCH

im using laravel/octobercms

**Comment by AnoopAlias** [comment]
Are you using High-Performance wordpress (wordpress+fastcgi cache) template?

**Comment by Teranode** [comment]
@AnoopAlias im using the laravel template. Im currently utilizing the laravel framework

**Comment by AnoopAlias** [comment]
http://stackoverflow.com/questions/37908967/express-and-nginx-neterr-content-length-mismatch .

The laravel template has no caching enabled in nginx. Try disabling pagespeed and see if that helps

**Comment by Teranode** [comment]
I don't have it enabled (never did), bt it still gives that kind of error

**Comment by AnoopAlias** [comment]
Try disabling brotli . Pagespeed is enabled at the server http level too. in 
/etc/nginx/conf.d/http_settings.conf

```
#Google PageSpeed (OptimizeForBandwidth)
include /etc/nginx/conf.d/pagespeed_default.conf;

```

Pagespeed,gzip/brotli are the stuff that modify the content before serving 


Also check the nginx error_log file and look for any errors.

You have to troubleshoot this with a trial and error method.

**Comment by Teranode** [comment]
@AnoopAlias does sendfile do anything? 
I turned it off and everything's normal so i want to know if it has any significance in anything

**Comment by AnoopAlias** [comment]
@Teranode - sendfile syscall is used to directly serve content

https://t37.net/nginx-optimization-understanding-sendfile-tcp_nodelay-and-tcp_nopush.html

**Comment by Teranode** [comment]
okay, so i re-enabled sendfile and then disabled the pagespeed conf and its now working

**Comment by Teranode** [comment]
And I have another question:

The cms im using is Octobercms, and in one of the config files theres an option to use flexible SSL. Basically I am able to go to https:// or http:// and the cms itself will detect when you ar on either and change the files being served respectively. When I do this with nginx this doesnt happen. Is there a way to have flexible http:// and https:// ?

**Comment by AnoopAlias** [comment]
the fastcgi_param file included for php location has
`fastcgi_param  HTTPS              $https if_not_empty;`

If your script use the above HTTPS variable to determine if the connection is SSL . It should work.

You must contact the script dev;s and identify if the script is fastcgi compatible.
