### ISSUE TITLE
Memcache for Nginx and PHP-FPM

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#11]
What is the supported way to install memcache for NginX & PHP-FPM?

**Comment by AnoopAlias** [comment]
same method as xcache 

php-fpm and all its modules must be installed from the remi scl repo's. or if not avilable compile from source or using pecl

**Comment by sergeng** [comment]
For the main MemcacheD
yum --disableexcludes=all --enablerepo=remi install memcached
OK

But for PHP-FPM
yum --disableexcludes=all --enablerepo=remi install php56-php-pecl-memcached
or
yum --disableexcludes=all --enablerepo=remi install php56-php-pecl-memcache
?

My App is built on Zend Framework 2, should i install
yum --disableexcludes=all --enablerepo=remi install php-ZendFramework2-Cache-memcached
Too?

**Comment by AnoopAlias** [comment]
This is not an nDeploy bug and github issues is meant for bug report .

SysAlly.net provides tech support at hourly support rate . We can assist you in this way if you email support@sysally.net

**Comment by sergeng** [comment]
For the record, i get it installed with
yum --disableexcludes=all --enablerepo=remi install php56-php-pecl-memcache

Thank you
