### ISSUE TITLE
cPanel 11.60 now available with PHP-FPM Pools

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#112]
@AnoopAlias,

Now that cPanel 11.60 is available with PHP-FPM pools available for Apache without a cumbersome configuration I wanted to give it a try to see how it performs for a few of my sites.

I setup a PHP-FPM pool for one of my sites and restarted NGINX & Apache, however, when checking a php info file for this site it doesn't appear to be using the revised configuration. nDeploy was already setup a PROXY backend.

Can you please advise on how this needs to be setup? If you leave me a note here I'll writeup documentation in `rst` for the docs site.

Thanks!

**Comment by AnoopAlias** [comment]
@brianjking - there is no need to restart apache/nginx . You must set PHP-FPM  to On in
WHM
Home »Software »MultiPHP Manager￼ 

for the domain in question

Once done you will have a file like the one below ( piserve.com is example)

/var/cpanel/userdata/piserve/piserve.com.php-fpm.yaml 

If you do this from frontend I think cPanel covers the creation of pool file and reloading the master process. 

This has nothing to do with nginx and the nDeploy pool or master php-fpm process created by nDeploy. 

cPanel has its own way to manage the pool file,reloading etc.

**Comment by brianjking** [comment]
Thanks @AnoopAlias
