### ISSUE TITLE
Duplicate Vary: Accept-Encoding Headers Sent

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#113]
````
curl -I https://duelingdogs.net                                                                                                                   19:31   17.10.16
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html
Connection: keep-alive
Vary: Accept-Encoding
Vary: Accept-Encoding, Cookie
X-Rocket-Nginx-Bypass: Yes
X-Rocket-Nginx-Reason: /wp-content/cache/wp-rocket/duelingdogs.net///index-https.html
X-Rocket-Nginx-File: /home/duelingdogs/public_html/wp-content/cache/wp-rocket/duelingdogs.net///index-https.html
Strict-Transport-Security: 0
Date: Tue, 18 Oct 2016 01:09:31 GMT
X-Page-Speed: 1.11.33.4-0
Cache-Control: max-age=0, no-cache
````

````
curl -I https://theupbeatk9.com/wp-content/plugins/monarch/js/idle-timer.min.js\?ver\=1.3.2                                                   16:58   17.10.16
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/javascript; charset=utf-8
Connection: keep-alive
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
X-Original-Content-Length: 2400
Vary: Accept-Encoding
Vary: Accept-Encoding
Content-Length: 2400
ETag: W/"PSA-aj-d1iP5JOS_N"
Date: Mon, 17 Oct 2016 21:58:38 GMT
Expires: Mon, 09 Oct 2017 16:36:34 GMT
Cache-Control: max-age=30825475, public
````

**Comment by AnoopAlias** [comment]
@brianjking - can you try disabling pagespeed module for the domain .

There is a default pagespeed setting in the main conf

in file /etc/nginx/conf.d/http_settings.conf

Comment out following lines and reload/restart nginx

```
#Google PageSpeed (OptimizeForBandwidth)
include /etc/nginx/conf.d/pagespeed_default.conf;

```

Let me know if that helps.

**Comment by brianjking** [comment]
@AnoopAlias Commenting out `include /etc/nginx/conf.d/pagespeed_default.conf;` in `/etc/nginx/conf.d/http_settings.conf` seems to resolve it. However, these domains already had pagespeed disabled as per the nDeploy settings in cPanel's UI.

**Comment by brianjking** [comment]
Sending these headers twice definitely isn't right, maybe there's a better way to do this?

**Comment by AnoopAlias** [comment]
@brianjking 
The On/Off via nDeploy is just removing/adding the include of pagespeed with optimizations enabled.
/etc/nginx/conf.d/pagespeed_default.conf is loading a bandwidth optimization only config that is stated to work for almost all users without issue. I am removing this in nDeploy4 in dev now as complete enable/diable is much cleaner.

As far as the headers are concerned . Issue is with pagespeed. 

https://github.com/pagespeed/ngx_pagespeed/issues/1064

**Comment by AnoopAlias** [comment]
Closing this as the default pagespeed setting is removed from nginx.conf in AnoopAlias/nDeploy/ndeploy4 branch . So you could disable pagespeed completely from cpanel
