### ISSUE TITLE
The Wiki pages down

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#117]
The Wiki page is down. Do you plan to restore it? Do you need any assistance in hosting it?

**Comment by ivangrynenko** [comment]
http://anoopalias.github.io/nDeploy/ shows 404 not found

**Comment by AnoopAlias** [comment]
@ivrh - Thanks for the heads up and apologies for the inconvenience. nDeploy has been renamed as XtendWeb .

I am working on the new documentation. If you want to access the old doc for the time being .

git clone https://github.com/AnoopAlias/XtendWeb.git
cd XtendWeb//docs/_build

and double click on the .html files.

I will make the new docs live shortly.

Thanks.

**Comment by ivangrynenko** [comment]
Maybe a good idea to update the Readme file for the repository with these commands?

Do you need to host the old docs until you restore them somewhere else? I can give you a free account in Australian server to host the HTML docs you have (temporarily or permanently) and you just re-point DNS. I can even upload the docs for you.

Let me know if that helps.

**Comment by AnoopAlias** [comment]
@ivrh  - The old docs were intentionally removed . readthedocs provided free doc hosting .

I will try to make the new docs available as soon as possible(mostly in the next 5-6 hours).

Thanks for the offer.

**Comment by AnoopAlias** [comment]
I have updated the info on how to access the old doc on the README file.
