### ISSUE TITLE
Rebooted Server & All Sites showing 503 errors until I reset PHP-FPM on each site individually

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#12]

**Comment by AnoopAlias** [comment]
Hello Brian,

I will try recreating this issue on our test environment

**Comment by brianjking** [comment]
@AnoopAlias Can you please advise on how I can mitigate this from happening again or quickly set all domains that use the PHP-FPM Proxy to Apache option by running a command from SSH?

**Comment by AnoopAlias** [comment]
Hi Brian,

What are the status of the symlinks in /var/run/fpmsockets/ when this happens . Do they exist ? if yes is the link target shown as valid?.

I suspect probably the ndeploy_backends script is not chlconfig-ed in.

chkconfig ndeploy_backends on

##

In worst case running

for CPANELUSER in $(cat /etc/domainusers|cut -d: -f1)
        do
            /opt/nDeploy/scripts/apache_php_config_generator.py $CPANELUSER
         done

Should take care of rebuilding the symlinks . 

I am yet to reproduce this on a server as I have had limited internet access for the past few days . I will test this thoroughly this weekend.

Thanks,
Anoop

**Comment by brianjking** [comment]
Any luck @AnoopAlias

**Comment by AnoopAlias** [comment]
Hello Brian,

Just found the root cause of the issue . I will provide a fix in the next rpm build . 

Thank you,
Anoop

**Comment by AnoopAlias** [comment]
Hello Brian,

Updated rpm is in place https://support.sysally.net/news/5

Please run the following commands in-order to reset the custom include in apache template .(after the new rpm is installed via yum)

/opt/nDeploy/scripts/apache_php-fpm_setup.sh disable
/opt/nDeploy/scripts/apache_php-fpm_setup.sh enable

**Comment by brianjking** [comment]
@AnoopAlias Attempting an upgrade now.

**Comment by brianjking** [comment]
After I run /opt/nDeploy/scripts/apache_php-fpm_setup.sh enable and select a php version it just hangs. sites are showing 503 errors. @AnoopAlias

**Comment by AnoopAlias** [comment]
Hi Brian,
Please add our key or pass on root login creds via our help desk and I will check this
Anoop
