### ISSUE TITLE
Nginx Configuration Fails Missing default_server.conf with most recent update -- URGENT

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#131]
````
[root@lw ~]# nginx -t
nginx: [emerg] open() "/etc/nginx/conf.d/default_server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/http_settings.conf:78
nginx: configuration file /etc/nginx/nginx.conf test failed
````

````
[root@lw ~]# yum info nDeploy
Loaded plugins: fastestmirror, priorities, protectbase, security, tsflags, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 208.100.0.204
 * epel: mirror.steadfast.net
 * remi-safe: ca.mirror.babylon.network
102 packages excluded due to repository priority protections
0 packages excluded due to repository protections
Installed Packages
Name        : nDeploy
Arch        : noarch
Version     : 4.0
Release     : 23.el6
Size        : 347 k
Repo        : installed
From repo   : ndeploy
Summary     : nDeploy cPanel plugin
URL         : http://anoopalias.github.io/XtendWeb/
License     : unknown
Description : nDeploy cPanel plugin
````

Looks like it's an issue others are having too based on [this thread](https://groups.google.com/forum/#!topic/gnusys_extendweb/rGeItfSHGB4).

**Comment by brianjking** [comment]
When attempting to run `attempt_autofix.sh` I'm also shown the error:

````nginx: [emerg] open() "/etc/nginx/conf.d/default_server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/http_settings.conf:78````

Based on viewing `http_settings.conf`, line 78 tells me that `default_server.conf` is generated during XtendWeb install, leaving me stuck. ☹️ 

https://github.com/AnoopAlias/XtendWeb/blob/ndeploy4/rpm_buildtree/nginx-pkg-64-common/etc/nginx/conf.d/http_settings.conf#L77-L79

@AnoopAlias Please help!

**Comment by AnoopAlias** [comment]
@brianjking 

Just run /opt/nDeploy/scripts/generate_default_vhost_config.py
