### ISSUE TITLE
CORS in PHP backend

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#133]
@AnoopAlias -- I'm having trouble getting CORS enabled again now that v4 is released.

**Comment by AnoopAlias** [comment]
@brianjking - You must create custom config with the CORS config included in location/{}
http://enable-cors.org/server_nginx.html
I can help here but it will be a commercial ad-hoc sysadmin service

**Comment by Denoder** [comment]
:/ i really dislike the fact that manual edit was removed

**Comment by AnoopAlias** [comment]
@Teranode - Manual edit is still there. but it has to be done from the CLI rather than the web UI.
Please see:  http://xtendweb.gnusys.net/XtendWeb_Administration.html#adding-application-templates
