### ISSUE TITLE
GZIP & VARY: Accept-Encoding not working by default

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#134]
With XtendWeb v4 configured with gzip = on for the domains set in the XtendWeb control panel sites were not showing a Vary: Accept-Encoding header and were not showing as being compressed by default using sites such as http://checkgzipcompression.com/ or Pingdom.

In order to get this to work I had to do the following:

* `/etc/nginx/conf.d/$ cp gzip.conf /etc/nginx/conf.auto`
* `/etc/nginx/conf.d/$ service nginx stop`
* `/etc/nginx/conf.d/$ service nginx start`

**Comment by AnoopAlias** [comment]
@brianjking - moving it to conf.auto gets it included always. What you can do is keep it in the conf.d itself and when gzip is set to on see the generated config file in /etc/nginx/sites-enabled/domain.conf and see if the gzip.conf is indeed getting included or not .

Also keep in mind that if you have brotli enabled ..and using TLS (https) ..gzip will be replaced by brotli compression .which probably may not be detected by the online test. You can specifically test for brotli in this case.
