### ISSUE TITLE
Upgrade planning. Extra preparation steps mising

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#135]
I am looking at the upgrade instructions http://xtendweb.gnusys.net/migrating_from_nDeploy.html

1. Existing accounts that bypass Apache
While it is clear that removing of nDeploy is required, it will break customer websites running via Nginx + PHP-FPM, so identification and reconfiguration of those accounts/websites is required. Could you update the documentation with the right order of actions to identify such domains that bypass Apache.

2. We have a number of templates customising Drupal and Joomla default ones to allow Drupal 8 BigPipe to work and Joomla to allow breezingforms plugin to show captcha (requires PHP to display an image).
Is there a way to re-use those templates? Or a manual upgrade will be required?

**Comment by AnoopAlias** [comment]
1. 
```
cd /opt/nDeploy/domain-data
grep -rl "backend_category: PHP" ./
```
will show all domains using PHP now

`grep -rl "customconf: '0'" ./`

will show domains having custom config edits . The current configuration is saved in /home/user/

2. You will need to create new templates with the changes as the old templates and new ones are not compatible. Note that you may not need to do it from scratch as the change mostly is how variables are declared etc .Like for example DOCUMENTROOT change to {{ DOCUMENTROOT }} .
So with a few changes you can mostly reuse the template. 
see: http://xtendweb.gnusys.net/XtendWeb_Administration.html#adding-application-templates
