### ISSUE TITLE
Implement redis wordpress cache with conditional purge

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#136]
https://easyengine.io/wordpress-nginx/tutorials/single-site/redis_cache-with-conditional-purging/

Require 4 additional modules

**Comment by AnoopAlias** [comment]
Done!

**Comment by brianjking** [comment]
@AnoopAlias In order to use the Redis Caching do we need to install the Nginx Helper still and activate the Redis Caching mechanism?

What else is required?

Thanks!

**Comment by AnoopAlias** [comment]
All steps mentioned in 
http://xtendweb.gnusys.net/PHP.html#high-performance-wordpress-setup-using-redis-cache-and-nginx-helper-plugin

install redis, install nginx modules, register the template , install helper and change settings (for cache purging)
