### ISSUE TITLE
Implement CDN

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#137]
Anoop, seee ticket ID ticket&id=3830, i can give 250 box, need other guy helping to fund.

HA Cluster is good, but why not making these slave servers work much more.... with CDN feature ? It seems DynDNS is needed...

I would like to see traffic redirected to closest server depending on visitor's continent... so that site is fast anywhere in the world... Actually with far end Asia, and USA, i get 5-10 second loading speed even with lightening ssd speedy server... I also tried CDN services with heaviest stored resources in their servers in 20 countries, i get worst performances than direct loading...
Then solution is to have its own small HA-cluster with geo traffic....

My main site server is in Europe, I'd like to setup a DNS server at west world in Singapore by example, and 1 DNS server at east world in Miami. Mysql server slave can be on Miami server by example,n or even a separate VPS in USA...

HA remarks :
If main server is down, or any slave servers , traffic must automatically redirect to any server which is UP and closed to visitor....

**Comment by ivangrynenko** [comment]
This looks like a custom use case, I can't think of having this feature as adding any value to the plugin.

Just use Cloudflare or similar to achieve transparent and zero-config CDN functionality.

**Comment by yoorshop** [comment]
I know what value it would be for me. I want it, and i will have it, is just a matter of time.
But If i pay this all myself in full, I will ask that system is private for me, and not opensource

Are you aware that we can't use cloudflare with SSL, unless you pay 200 box per month ?

Have you seen how I have formulated the script to work in details, this is high performance with no comparison cumulated with HA, nothing at cloudlare will give you such level for dynamic sites....

**Comment by ivangrynenko** [comment]
A number of issues create custom feature requests:
1. Your custom script will not be widely used since it is very limited use cases
2. Custom code increases complexity and create maintainability problem. The plugin will be more difficult to maintain

Cloudflare is completely free with their SSL,
Keepign XtendWeb dedicated to what it does is critical to ensure fast issue resolution and timely bug fixes, updates. 
Rather than add limited use case features (even when you provide ready to use code) creates maintenance burden and block critical features and bug updates. 

Think of it this way: feature like yours will require a new developer to keep it up to date and work on problems/bugs it creates in XtendWeb or in itself.

**Comment by AnoopAlias** [comment]
For time being you can use an external LB DNS service 
https://www.maxcdn.com/blog/dns-load-balancing-comparison-4-services/

**Comment by yoorshop** [comment]
Please speak English :)

**Comment by AnoopAlias** [comment]
The sites mentioned in that link provide geo-directed , Load balanced DNS (with health check) for a price ( say like 2 USD for 1 domain/zone) . The only thing awkward will be that you need to configure the  DNS service manually,Whereas the XtendWeb cluster will add multiple A records (to cpanel DNS cluster) automatically thus making it a maintenance free setup.

**Comment by yoorshop** [comment]
ok, no, i want a better solution home made, and paid 1 time :)

**Comment by yoorshop** [comment]
'Cloudflare is completely free with their SSL,' :
Completely wrong
Do you know how much it costs custom SSL with CDN ? 200$ /mo
Even if it was free, their service is reducing performance on websites, I made a deep study with precise numbers on this...

This feature would make unique XTendWeb, we need a solution hassle free for DNS...

**Comment by AnoopAlias** [comment]
Checked out EdgeDetector . The API seem to be only allow/modify DNS records.
Service tests , location etc need to be configured manually for each zone in the User Interface .

**Comment by AnoopAlias** [comment]
edgedirector*

**Comment by yoorshop** [comment]
You say 'seem', we can't be based on seem. Their service is complex, and can be used several ways.
Please ask their support about what we want to do exactly, they can help deeply.

**Comment by AnoopAlias** [comment]
#293 will bring a closure to this. Issue will be further tracked in #293
