### ISSUE TITLE
WHM/cPanel SSL serving old certificate

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#138]
Is Nginx proxying WHM ports at all? I have a strange issue where updating SSL certificate for WHM is still loading the old certificate.

However when accessing via /cgi-sys/defaultwebpage.cgi or IP address, the correct SSL is displayed.

**Comment by ivangrynenko** [comment]
In fact I found it by inspecting httpd.conf which had vhost for WHM and other cPanel services, I have found that the /etc/nginx/conf.d/default_server.conf was using wrong SSL, so I assume the plugin is not updating it, when a new SSL is installed for WHM/cPanel.

Even though I have nDeploy and yet to upgrade (sadly no LTS for nDeploy) to XtendWeb, this issue may exist in the latest XtendWeb plugin.

**Comment by AnoopAlias** [comment]
You may just need to run 
nginx -s reload

**Comment by ivangrynenko** [comment]
Would this change the /etc/nginx/conf.d/default_server.conf file? I doubt so. It is rather cPanel hook implementation missing somewhere, preventing certificate update for WHM/cPanel.
It is fixed now, but I was suggesting you try replicating it by installing a new SSL and review if the /etc/nginx/conf.d/default_server.conf reflects it

**Comment by AnoopAlias** [comment]
The cpanel cert path is /var/cpanel/ssl/cpanel/mycpanel.pem ( for custom ) or /var/cpanel/ssl/cpanel/cpanel.pem . The path dont change. You can generate the default config anytime using
`/opt/nDeploy/scripts/generate_default_vhost_config.py`

I dont think cPanel has hook for WHM/System cert update .

**Comment by ivangrynenko** [comment]
Thank you. 
Maybe you should add this to the documentation then, how to renew SSL for WHM/cPanel and related services - to run the `/opt/nDeploy/scripts/generate_default_vhost_config.py` scrypt

**Comment by AnoopAlias** [comment]
@ivrh - This is now available as a tip at http://xtendweb.gnusys.net/installation.html
