### ISSUE TITLE
Subdomain mail 

### ISSUE THREAD

**Issue by bashcode** [AnoopAlias/nDeploy#143]
Hello,

Is posible to remove proxy for mail.domain.com in XtendWeb, because is not redirecting correctly on cPanel servers.

Thanks

**Comment by AnoopAlias** [comment]
You mean in the nginx config?.

XtendWeb does not do any logic in the construction of alias domains. It takes whatever is recorded by Cpanel in userdata.

**Comment by AnoopAlias** [comment]
I am closing this issue due to lack of clarity on the request
