### ISSUE TITLE
[Question] Disable XtendWeb for individual accounts

### ISSUE THREAD

**Issue by Denoder** [AnoopAlias/nDeploy#145]
is there a way for you to disabled the proxy/php-fpm for individual accounts?

**Comment by AnoopAlias** [comment]
You can disable the plugin in entire.
Proxy is transparent ..so in effect HTTPd is serving the request just like if you hadn't installed Xtendweb. Only if you switch to php (native nginx)mode things are different . I am not quite certain what you really meant . But nginx will always be the Front-end webserver when the plugin is enabled.
