### ISSUE TITLE
Whmcs ip

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#146]
Whmcs get the IP of the users but now this showing all the users with the own ip of the server

**Comment by AnoopAlias** [comment]
XtendWeb generate nginx config from website IP mentioned in /var/cpanel/userdata/ . The generated config in /etc/nginx/sites-enabled should have the IP's mentioned in userdata files. Dont they match?

**Comment by AnoopAlias** [comment]
Closing this for the lack of further update
