### ISSUE TITLE
SSL cert install needs manual config generation

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#15]
The problem lies in the fact that SSL certificate install does not provide any hooks in their API by cPanel.

Currently we use inotify and incron on /var/cpanel/users/<USER> file to detect cpanel events with no hooks and fire a reconfiguration . The problem is that cPanel doesnt change <USER> files in SSL cert installation. But cPanel do change yaml files in /var/cpanel/userdata for all our usecases . 

Why not use inotify to watch /var/cpanel/userdata ? - Well inotify doesnt support recursive file events and /var/cpanel/userdata has subdirectories where events happen . 

So the solution ? - Write a custom inotify daemon to listen recursively on /var/cpanel/userdata or use ready-made scripts like https://github.com/gregghz/Watcher .

This is targeted for the next release of nDeploy plugin .

**Comment by brianjking** [comment]
How can I install an SSL certificate that is self signed on a domain using php-fpm? @AnoopAlias

**Comment by AnoopAlias** [comment]
Just install it normally . self signed or CA signed has no implication for php-fpm
