### ISSUE TITLE
php website File not found

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#154]
Dumb to php on website passing hours site presents error File not found

**Comment by AnoopAlias** [comment]
Whats the error in nginx error_log?

**Comment by weltonwe** [comment]
Here is the error log https://drive.google.com/file/d/0B6SQACpnZg7qaXhOMG9reF95Yzg/view?usp=sharing

**Comment by weltonwe** [comment]
How to configure default error pages

**Comment by AnoopAlias** [comment]
you can google nginx+default error pages and can adapt the tutorials to XtendWeb by adding them in the application template. The error log provided is very big and I see numerous error relating to passenger setup etc. Not sure how you set it up. But somethings not definitely right
