### ISSUE TITLE
XtendWeb Remove Problem. 

### ISSUE THREAD

**Issue by mhhakim** [AnoopAlias/nDeploy#157]
Dear AnoopAlias,
When I try to remove xtendweb, it showing this error. The plugin doesn't remove.
I was deleted 1 website configuration file from /etc/nginx/sites_enabled because that website showing Bad gatway error. Then I try to re generate config by running common problem fixing command. But it showing 2 file missing error that I have deleted. Than I re create the files. After that problem was fixed. But now the problem is, XtenWeb control link missing on cPanel. For this I want to uninstall than install again XtenWeb.  But showing following error.

`[root@server IP ~]# yum remove nginx-nDeploy nDeployLoaded plugins: fastestmirror, universal-hooksResolving Dependencies--> Running transaction check---> Package nDeploy.noarch 0:4.1-3.el7 will be erased---> Package nginx-nDeploy.x86_64 0:1.11.9-1.el7 will be erased--> Finished Dependency ResolutionDependencies Resolved============================================================================= Package             Arch         Version               Repository      Size=============================================================================Removing: nDeploy             noarch       4.1-3.el7             @ndeploy       406 k nginx-nDeploy       x86_64       1.11.9-1.el7          @ndeploy       3.0 MTransaction Summary=============================================================================Remove  2 PackagesInstalled size: 3.4 MIs this ok [y/N]: yDownloading packages:Running transaction checkRunning transaction testTransaction test succeededRunning transaction Removing cpanel hooksProvided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Cpanel" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Stats" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Stats" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "System" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "Whostmgr" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "ConvertAddon" does not exist in hooks registry (this may indicate that the specified hook is not installed)Provided category of "ConvertAddon" does not exist in hooks registry (this may indicate that the specified hook is not installed) Uninstalling nDeploy plugin in cPanelPlugin uninstalled okerror: %preun(nDeploy-4.1-3.el7.noarch) scriptlet failed, exit status 1Error in PREUN scriptlet in rpm package nDeploy-4.1-3.el7.noarcherror: nDeploy-4.1-3.el7.noarch: erase failed  Erasing    : nginx-nDeploy-1.11.9-1.el7.x86_64                         1/2   Verifying  : nDeploy-4.1-3.el7.noarch                                  1/2   Verifying  : nginx-nDeploy-1.11.9-1.el7.x86_64                         2/2 Removed:  nginx-nDeploy.x86_64 0:1.11.9-1.el7                                        Failed:  nDeploy.noarch 0:4.1-3.el7                                                 Complete![root@ip ~]`

**Comment by AnoopAlias** [comment]
You should disable plugin first. It removes it completely out of the way and is easier when you troubleshoot etc. Removing removes the files etc.

You can use normal rpm commands to remove like rpm -e --no-scripts. 

You can also opt for paid assistance for correctly setting up the plugin and optimizing the stack if you purchase a support plan at https://support.gnusys.net/order.php .

**Comment by mhhakim** [comment]
Problem almost solved. I can access XtendWeb by adding `nDeploy_cp/xtendweb.live.py` on url. Only link is missing on cPanel.

**Comment by AnoopAlias** [comment]
yum --enablerepo=ndeploy reinstall nDeploy

**Comment by mhhakim** [comment]
Everything is perfect now !
Thanks.
