### ISSUE TITLE
erro restart off server off

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#159]
nginx: [emerg] BIO_new_file("/etc/nginx/ssl/dhparam.pem") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/nginx/ssl/dhparam.pem', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)

**Comment by AnoopAlias** [comment]
This file should be created on rpm install. Not sure why its missing!

**Comment by weltonwe** [comment]
I removed and installed again appears this error I solved catching the key of another server is placing in this archi dhparam.pem
