### ISSUE TITLE
mod_remoteip is not working

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#160]
In a fresh install of XtendWeb with mod_remoteip I still see the server's main IP being logged in Apache domlogs for accounts.

The module is loaded - confirmed via apachectl -M
The Include is added into post_virtualhost global include - I see it there.

Looking at the include file, the log format seem correct, the same works in other servers with no cPanel and with Nginx.

Any ideas?

**Comment by AnoopAlias** [comment]
Is the include file automatically populated with all the IP address on the server?
Also ensure the log-format update done at /etc/nginx/conf.d/httpd_mod_remoteip.include is not overridden by any other setting

**Comment by ivangrynenko** [comment]
Looks like the include files are not included at all. Clarifying this via cPanel forums.
