### ISSUE TITLE
pagespeed is not working

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#161]
I have a recent install of XtendWeb, with pagespeed installed from your repository as instructed.

However no pagespeed include or directives exist, nor it worsk. The pagespeed option is selected for the site I am trying to resolve this for.

`[root@cpanel nginx]# pwd

/etc/nginx

[root@cpanel nginx]# grep -lir 'speed' *

modules/ngx_http_brotli_filter_module.so

[root@cpanel nginx]# `

**Comment by AnoopAlias** [comment]
pagespeed include file is included only on the server context if the user/domain has eabled pagespeed in XtendWeb server settings.

**Comment by AnoopAlias** [comment]
# rpm -qf /etc/nginx/conf.d/pagespeed.conf 
nginx-nDeploy-module-pagespeed-1.11.9-1.el7.x86_64
