### ISSUE TITLE
Missing max-age for static files

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#162]
When using Nginx with ndeploy-backends (PHP mode) - Nginx configuration does not include the max-age headers to facilitate client-side static files cache.

This downgrades sites speed ranking in many systems (google ranking, alexa ranking etc.).

So I have to switch to Apache so that directives setting max expiration time for static files could be used.

This is what I am referring to:
<FilesMatch "\.(jpg|jpeg|png|gif|swf)$">
  Header set Cache-Control "max-age=32400000, public"
</FilesMatch>

Nginx equivalent is
location ~* \.(gif|jpg|otherstaticfilesimagescssjs)(\?[a-zA-Z0-9\.\-_,])?$ {
  expires max;
  add_header Cache-Control "public";
}

Would you be able to add this to one of the templates to facilitate static files cache by web browsers?

**Comment by AnoopAlias** [comment]
I believe the expires header set does the same job.

I any case you can register templates based on the existing templates ,with the changes you need

**Comment by AnoopAlias** [comment]
The expires directive is included in most templates. If you need additional setting this can always be implemented via a custom template.

**Comment by ivangrynenko** [comment]
I don't think this is a custom setup I was talking about. I just switched one of websites to Nginx + PHP and Drupal template.

All I have is:
location ~* \.(js|css|png|jpg|jpeg|gif|swf|xml|ico|pdf|flv|txt)$ {
expires 1d;
}

But this won't work in most cases, since:
1. Drupal uses ?itok= query string on all images 
2. It is only 1 day static caching.

Of course I could use custom templates, but this will make it too hard keeping up with future template updates.

**Comment by AnoopAlias** [comment]
Ok got it. I have created a new branch ndeploy4new to fix some other issues and have more capabilities provided in the GUI. I will add the static file expires setup as an on/off option.

**Comment by AnoopAlias** [comment]
@ivrh - I think having the query string in the css/js is necessary and used as a cache buster?

http://stackoverflow.com/questions/24354119/why-do-developers-append-a-query-string-in-javascript-files-stylesheet-links

So 
```

location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
    expires 30d;
    add_header Pragma public;
    add_header Cache-Control "public";
    try_files $uri =404;
}

```

is enough I guess?

**Comment by ivangrynenko** [comment]
Hi Anoop.

Sorry to reopen this. What you suggest is basically means no caching for Drupal, since EVERY static file comes with `itok` query string. The itok value changes every time Drupal caches are cleared.

I our experience with Nginx and Drupal and Wordpress, query string has to be included and cached (or made selective via the interface).

So, without `(?[a-zA-Z0-9.-_,])?$` Drupal sites will get downranked by Google for lack of cache expiration headers (we do this for years, but you could check it via https://www.webpagetest.org/ with Drupal 6, 7, 8 - receives D rank for static files cache.

**Comment by AnoopAlias** [comment]
@ivrh - I trust your expertise here. I just didn't want to break something that the application designers have included to evade caching.  But since Xtendweb is all about squeezing out the best possible performance from a cPanel server. I will include this in next version(currently in dev as some change in UI etc is pending)
https://ma.ttias.be/drupals-itok-parameters-explained-varnish-workaround-different-backends/ - also confirms this is fine.

**Comment by AnoopAlias** [comment]
nginx: [emerg] pcre_compile() failed: unrecognized character after (? or (?- in "\.(?:ico|css|js|gif|jpe?g|svg|png)(?[a-zA-Z0-9.-_,])?$" at "[a-zA-Z0-9.-_,])?$" in /etc/nginx/conf.d/files_with_expire.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed


Getting the above in tests. I am reverting the changes

**Comment by AnoopAlias** [comment]
Closing this . The regex you provided has som issue which can be tested here: https://regex101.com/

I think 

`\.(?:ico|css|js|gif|jpe?g|svg|png)(\?[a-zA-Z0-9.-_,])?$`

is what you intended ? . as otherwise the question mark will be treated as a regex. I think I will stick to whatever is mentioned in majority of the docs for expire setting which just check for the file extension and not the args after
