### ISSUE TITLE
Error rpm

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#164]
exe:/usr/sbin/nginx
/var/tmp/rpm-tmp.Ah4FG4: line 18: openssl: command not found
warning: %post(nginx-nDeploy-1.11.9-2.el7.x86_64) scriptlet failed, exit status 127
Non-fatal POSTIN scriptlet failure in rpm package nginx-nDeploy-1.11.9-2.el7.x86_64
  Installing : nDeploy-4.1-5.el7.noarch

**Comment by henriqueccruz** [comment]
Your installation is missing openssl somehow. Try running locate openssl to check if it's installed and maybe create a symlink from /usr/bin

**Comment by weltonwe** [comment]
How do I create this symbolic link?

**Comment by AnoopAlias** [comment]
your cpanel install looks broken . openssl should be there in your path!

**Comment by weltonwe** [comment]
I only have one thing to declare soble this pluguin do not install it if you have client because you will lose all your clients if they start working with it your server will not even open a page it does not work with php

**Comment by AnoopAlias** [comment]
You should opt for paid support if you are not sure of what you are doing
