### ISSUE TITLE
No support to Public-Key-Pins

### ISSUE THREAD

**Issue by henriqueccruz** [AnoopAlias/nDeploy#165]
Hi guys, this is a possible improvement.

HTTP Public Key Pinning protects your site from MiTM attacks using rogue X.509 certificates. By whitelisting only the identities that the browser should trust, your users are protected in the event a certificate authority is compromised.

This would pretty much take the plugin to another level, I think.

**Comment by AnoopAlias** [comment]
I dont see a huge gain with this given the fact that browser support is also not widespread.
https://scotthelme.co.uk/hpkp-http-public-key-pinning/ - looks like one of the best docs for this.
I also see this as a Feature request in cPanel
