### ISSUE TITLE
frontend/paper_lantern/nDeploy_cp/server_settings.live.py

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#166]
Python 2.7.5: /usr/bin/python
Tue Feb 14 21:58:48 2017
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /usr/local/cpanel/base/frontend/paper_lantern/nDeploy_cp/server_settings.live.py in ()
     72             yaml_parsed_profileyaml = yaml.safe_load(profileyaml_data_stream)
     73         # Server Settings
=>   74         naxsi = yaml_parsed_profileyaml.get('naxsi')
     75         naxsi_mode = yaml_parsed_profileyaml.get('naxsi_mode')
     76         autoindex = yaml_parsed_profileyaml.get('autoindex')
naxsi undefined, yaml_parsed_profileyaml = None, yaml_parsed_profileyaml.get undefined
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get' 
      args = ("'NoneType' object has no attribute 'get'",) 
      message = "'NoneType' object has no attribute 'get'"

**Comment by AnoopAlias** [comment]
Can you paste here the contents of file

/opt/nDeploy/domain-data/domain.com

Where domain.com is the problem domain

**Comment by AnoopAlias** [comment]
Closing this due to lack of response
