### ISSUE TITLE
need nginx? and install problems

### ISSUE THREAD

**Issue by jots** [AnoopAlias/nDeploy#17]
Hello,

I got a few errors during install, I don't have them now, but I know one of them was because I already had a /usr/local/apache/conf/includes/pre_virtualhost_global.conf  and it  didn't add a newline before adding:
SetEnvIf X-Forwarded-Proto https HTTPS=on

Are we supposed to have a directory for fpm pools configuration per user?  where do I find that?  

I see large directory trees at /opt/remi/  what are those about?

where do I find the apache config for how it hooks into php-fpm socket?

Do we need to use nginx?  Is there a way to just use straight apache with fpm?  What does nginx buy us?

How can I tell if a page is being served up by fpm?

thanks.

**Comment by AnoopAlias** [comment]
Hi 

In https://github.com/AnoopAlias/nDeploy/blob/master/scripts/cpanel-nDeploy-setup.sh line #39 you can see echo "SetEnvIf X-Forwarded-Proto https HTTPS=on" >> /usr/local/apache/conf/includes/pre_virtualhost_global.conf

which should! add that to a new line. Not sure why it messed up for you.

----
fpm pools are in PHP_ROOT/etc/php-fpm.d/ . pool config is created dynamically by the script.

----
Thats the RPM tree installed from the safe_remi repo . Its  https://www.softwarecollections.org/en/ by remi 
----
In the main httpd.conf ! . Configs are hooked there from the apache template files in /var/cpanel/templates/ . 
----
nDeploy currently is setup that way.But if you use the defalt PROXY setup..it is doing a transparent proxy and passing everything as is to apache .So we can safely say apache is serving straight in this mode.
----
Check the SAPI in a phpinfo page.It should say FPM

Thank you
