### ISSUE TITLE
WordPress Admin Ajax giving error

### ISSUE THREAD

**Issue by AminulBD** [AnoopAlias/nDeploy#170]
Hello,

First of all, you did amazing work!

I've installed XtendWeb in my cPanel everything working great as expected. But, Today I see there is an error on WordPress ajax process which is little long.

I get this error on the console

`net::ERR_INCOMPLETE_CHUNKED_ENCODING`

Do, you which part of XtendWeb Nginx causes this issue?

Thank you.

**Comment by AnoopAlias** [comment]
@AminulBD - Try disabling pagespeed/gzip/brotli in server setting. see if that fix it
Also googling the error says it might be a browser issue too. Try in a different browser and check Nginx error log too when the error happens

**Comment by AminulBD** [comment]
@AnoopAlias I tried google before posted here :) Let me check by disabling pagespeed/gzip/brotil.

**Comment by AminulBD** [comment]
This issue only with google chrome and which is little long. I think, need improvement but not at all.

I'm closing this issue since there are no need solutions.
