### ISSUE TITLE
XtendWeb cluster setup

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#171]
fatal: [xxxxxxx.xxxxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_nodename'"}

**Comment by AnoopAlias** [comment]
I think you have issue with your host (most probably hostname ) setup.

**Comment by weltonwe** [comment]
TASK [install_slave : Install nDeploy cluster slave rpm packages] **************
failed: [mx5.cpanel.org.es] (item=[u'csync2-nDeploy', u'unison-nDeploy', u'nginx-nDeploy', u'nDeploy-cluster-slave']) => {"changed": true, "failed": true, "item": ["csync2-nDeploy", "unison-nDeploy", "nginx-nDeploy", "nDeploy-cluster-slave"], "msg": "\n\nTransaction check error:\n  file /opt/nDeploy/README.md from install of nDeploy-cluster-slave-4.0-5.el7.noarch conflicts with file from package nDeploy-4.1-7.el7.noarch\n\nError Summary\n-------------\n\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirrors.prometeus.net\n * epel: mirror.de.leaseweb.net\n * extras: mirrors.prometeus.net\n * updates: mirrors.prometeus.net\nResolving Dependencies\n--> Running transaction check\n---> Package csync2-nDeploy.x86_64 0:2.0-5.el7 will be installed\n--> Processing Dependency: librsync for package: csync2-nDeploy-2.0-5.el7.x86_64\n---> Package nDeploy-cluster-slave.noarch 0:4.0-5.el7 will be installed\n---> Package nginx-nDeploy.x86_64 0:1.11.10-3.el7 will be installed\n---> Package unison-nDeploy.x86_64 0:2.48.4-1.el7 will be installed\n--> Running transaction check\n---> Package librsync.x86_64 0:1.0.0-1.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                    Arch        Version              Repository    Size\n================================================================================\nInstalling:\n csync2-nDeploy             x86_64      2.0-5.el7            ndeploy      178 k\n nDeploy-cluster-slave      noarch      4.0-5.el7            ndeploy       31 k\n nginx-nDeploy              x86_64      1.11.10-3.el7        ndeploy      8.4 M\n unison-nDeploy             x86_64      2.48.4-1.el7         ndeploy      1.9 M\nInstalling for dependencies:\n librsync                   x86_64      1.0.0-1.el7          epel          53 k\n\nTransaction Summary\n================================================================================\nInstall  4 Packages (+1 Dependent package)\n\nTotal size: 10 M\nTotal download size: 8.4 M\nInstalled size: 24 M\nDownloading packages:\nRunning transaction check\nRunning transaction test\n"]}
        to retry, use: --limit @/opt/nDeploy/conf/nDeploy-cluster/cluster.retry
