### ISSUE TITLE
HHVM returning error 500 for a single user

### ISSUE THREAD

**Issue by henriqueccruz** [AnoopAlias/nDeploy#172]
Error on log is:
`Failed to initialize central HHBC repository:\n  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file\n  Failed to open /var/cache/nginx/.hhvm.hhbc: 14 - unable to open database file\n
`

Tried regenerating user conf, no luck. Any clues?

**Comment by henriqueccruz** [comment]
Also worth noting: I'm not running HHVM as nobody. It's listed on my backend, I tried removing it but couldn't.
Anyways, /opt/nDeploy/hhvm.d/user.ini exists and seems to be okay, but isn't being loaded somehow.
Need help.

**Comment by AnoopAlias** [comment]
hhvm running as user need centos7 (systemd)

Paste here output of

`systemctl status ndeploy_hhvm@cpaneluser.service`

Where cpaneluser is substituted with the real user name

**Comment by henriqueccruz** [comment]
Output is as below
`
ndeploy_hhvm@visitandoit.service
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_hhvm@.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-03-07 03:37:14 BRT; 21min ago
 Main PID: 685163 (hhvm)
   CGroup: /system.slice/system-ndeploy_hhvm.slice/ndeploy_hhvm@visitandoit.service
           └─685163 /usr/local/bin/hhvm --config /opt/nDeploy/hhvm.d/visitandoit.ini --user visitandoit --mode daemon`

`Mar 07 03:41:23 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:41:23 2017] [hphp] [685163:7f07423ff700:22:000003] [] Finished singleJitRequest 11
Mar 07 03:41:24 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:41:24 2017] [hphp] [685163:7f07423ff700:23:000003] [] Finished singleJitRequest 12
Mar 07 03:41:45 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:41:45 2017] [hphp] [685163:7f07423ff700:24:000003] [] Finished singleJitRequest 13
Mar 07 03:41:47 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:41:47 2017] [hphp] [685163:7f07423ff700:25:000003] [] Finished singleJitRequest 14
Mar 07 03:41:49 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:41:49 2017] [hphp] [685163:7f07423ff700:26:000003] [] Finished singleJitRequest 15
Mar 07 03:42:24 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:42:24 2017] [hphp] [685163:7f07423ff700:27:000003] [] Finished singleJitRequest 16
Mar 07 03:42:26 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:42:26 2017] [hphp] [685163:7f07423ff700:28:000003] [] Finished singleJitRequest 17
Mar 07 03:42:56 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:42:56 2017] [hphp] [685163:7f07423ff700:29:000003] [] Finished singleJitRequest 18
Mar 07 03:42:58 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:42:58 2017] [hphp] [685163:7f07423ff700:30:000003] [] Finished singleJitRequest 19
Mar 07 03:43:02 ln77.intelihost.com.br hhvm[685163]: [Tue Mar  7 03:43:02 2017] [hphp] [685163:7f07423ff700:31:000003] [] Finished singleJitRequest 20`

**Comment by AnoopAlias** [comment]
that means hhvm is running ok. Your script may not be compatible with hhvm. 

Put  a simple phpinfo(); function and see if that works. Not every script that works in php works in hhvm. if you are using wordpress etc , core may work , but some modules may not. 

check nginx error log for more info on the error. contact the script vendor and discuss hhvm readiness

**Comment by henriqueccruz** [comment]
The strange thing is that the website worked under HHVM for a while and stopped suddenly.

**Comment by AnoopAlias** [comment]
500 error is app error. You need to check the logs
