### ISSUE TITLE
Is it possible to send API-like remote commands?

### ISSUE THREAD

**Issue by henriqueccruz** [AnoopAlias/nDeploy#175]
I'm programming my client area, and I'd like to offer my clients the ability to change Xtendweb settings right from the panel which is WHMCS based.
Can we use some sort of API to send remote commands, like changing settings and backends?

I think that can be really useful.

**Comment by AnoopAlias** [comment]
Right now XtendWeb is running any daemon and is a collection of scripts that execute on and taps into the cPanel hooks and API's . I am not sure how the WHMCS based UI works ..but if its using cPanel API's to login to cPanel area..I think it will be able to open up :2083/cpsessxxxxxxxx/frontend/paper_lantern/nDeploy_cp/xtendweb.live.py

You could include that in a frame or something? or just open up the URL in a new browser window

**Comment by henriqueccruz** [comment]
Hm well, not really.
Yes, it's using cPanel API to connect, and I'm trying to do something similar to XtendWeb. Provide application profiles, Nginx settings (like Brotli, SSL offload and header options), backend switch buttons, NAXSI Firewall settings, right from the Client Area.

What do you think?

**Comment by AnoopAlias** [comment]
@rickhessmann - Providing an API service for this while feasible is not in my top priorities right now.But I would surely consider this as a future enhancement.Right now since the Xtendweb UI opens in a new tab anyways can you see if you can open /nDeploy_cp/xtendweb.live.py in a new tab from the Billing system after cPanel API auth

**Comment by henriqueccruz** [comment]
Awesome, @AnoopAlias.
Opening the UI in a new tab/iframe is not really an option for me, as I'd like to provide deeper integration within my control panel.

Can you point me in the right direction? Should I learn python?

**Comment by henriqueccruz** [comment]
Hi @AnoopAlias, I'm a bit confused as to how your solution will work.
Can I continue to use it freely?

**Comment by AnoopAlias** [comment]
@henriqueccruz - The software is free and open source . The packaged product provided in the rpm repo needs a small license of 5 USD . This is similar to how RHEL works .

**Comment by henriqueccruz** [comment]
Nice. Can we still get updates using yum?

**Comment by AnoopAlias** [comment]
As long as you have a valid subscription ..you will have access to the repo.

**Comment by henriqueccruz** [comment]
I see. Well, how can I help with the API development? Where should I begin?

**Comment by AnoopAlias** [comment]
On top right extreme ..you will see a fork button.click on that .You will have a forked copy of the repo. You can make any changes to your fork and once you are done send me a pull request 

https://help.github.com/articles/creating-a-pull-request/

Thats it

**Comment by AnoopAlias** [comment]
Closing.. you can integrate WHMCS to XtendWeb using cPanel plans
Each hosting plan can be linked to a XtendWeb template/backend
