### ISSUE TITLE
nginx reload loop

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#184]
This is looping during hour son busy servers with 1000 sites on it
/usr/sbin/nginx -s reload

It happens at time when stats are procesed daily overnight by cpanel

**Comment by yoorshop** [comment]
we were using in the past this from WHM

Allow Awstats configuration Include file
Awstats Include file option will allow a user defined configuration file to be included at the time of statistics processesing. The include file should be place in the user's home directory at ~/tmp/awstats/awstats.conf.include. This file can be used to override and add new configuration options to Awstats.

Can't it prevent issue ?

**Comment by AnoopAlias** [comment]
After stats are processed ..the access log files are recreated .nginx will still hold to the old file descriptors and thus new logs wont be written. to get the new fd nginx has to restart or reload.

nginx -s reload is a normal event and should not cause any issues
