### ISSUE TITLE
ConfGen

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#186]
ConfGen:: ebooksmaniacom
Traceback (most recent call last):
  File "/opt/nDeploy/scripts/generate_config.py", line 594, in <module>
    nginx_confgen(is_suspended, clusterenabled, *cluster_serverlist, configuser=cpaneluser, configdomain=main_domain, maindomain=main_domain)  # Generate conf for main domain

**Comment by AnoopAlias** [comment]
Need full error as usually the exact error is printed in the last few lines .
