### ISSUE TITLE
Strange line

### ISSUE THREAD

**Issue by mdpuma** [AnoopAlias/nDeploy#19]
What's going on here

https://github.com/AnoopAlias/nDeploy/blob/master/scripts/event_trigger.sh#L10 (after &&)

Why you execute domain-data file ?

**Comment by AnoopAlias** [comment]
This script is triggered from watcher.py  https://github.com/AnoopAlias/nDeploy/blob/master/conf/jobs.yml
So if there is a domain name (Subdomain,addon domain etc) deleted from cPanel ..the event will get registered as IN_DELETE and this can be removed from nDeploy domain-data and nginx conf as well . Previously I used to leave these stale domains there itself which is fine .But this is much cleaner

**Comment by mdpuma** [comment]
rm -f /etc/nginx/sites-enabled/$THEDOMAIN\.* && /opt/nDeploy/domain-data/$THEDOMAIN
With this line you remove force /etc/nginx/sites-enabled/$THEDOMAIN\.* after that you execute /opt/nDeploy/domain-data/$THEDOMAIN not remove file after &&

**Comment by AnoopAlias** [comment]
@mdpuma .Thanks .Fixed it :)
