### ISSUE TITLE
Access to old gGroup Forum

### ISSUE THREAD

**Issue by 0rlan3o** [AnoopAlias/nDeploy#190]
Hello,

Is there a way to have access to the old google group tichets?

**Comment by AnoopAlias** [comment]
@0rlan3o - if you have a specific case in mind google the details + xtendweb and you will find a google cached copy

**Comment by AnoopAlias** [comment]
@0rlan3o  - Unfortunately I am fully into this software and support for the project and in general is my sole source of income. A 10 USD license would be practical only if I have like 1000 clients which I don't have. For 75 USD you will get support for your entire infra, not just one server.
