### ISSUE TITLE
Bug start nginx centos 7 VPS

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#191]
This is a fresh install with no customization.

I fixed manually issue with default_server.conf, script was not working : /opt/nDeploy/scripts/generate_default_vhost_config.py

[root@rep1 ~]# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

[root@rep1 ~]# service nginx restart
Redirecting to /bin/systemctl restart  nginx.service
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
[root@rep1 ~]# ^C
[root@rep1 ~]# systemctl status nginx.service
* nginx.service - nginx-nDeploy - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2017-04-09 06:04:59 CEST; 6s ago
     Docs: http://nginx.org/en/docs/
  Process: 2715 ExecStartPre=/usr/sbin/sysctl -w net.core.netdev_max_backlog=16384 (code=exited, status=255)
  Process: 2712 ExecStartPre=/usr/sbin/sysctl -w net.core.somaxconn=16384 (code=exited, status=0/SUCCESS)

Apr 09 06:04:59 rep1 systemd[1]: Starting nginx-nDeploy - high performance .....
Apr 09 06:04:59 rep1 sysctl[2712]: net.core.somaxconn = 16384
Apr 09 06:04:59 rep1 sysctl[2715]: sysctl: permission denied on key 'net.co...g'
Apr 09 06:04:59 rep1 systemd[1]: nginx.service: control process exited, code 255
Apr 09 06:04:59 rep1 systemd[1]: Failed to start nginx-nDeploy - high perfo...r.
Apr 09 06:04:59 rep1 systemd[1]: Unit nginx.service entered failed state.
Apr 09 06:04:59 rep1 systemd[1]: nginx.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by AnoopAlias** [comment]
Comment out the 

`ExecStartPre=/usr/sbin/sysctl `

lines in the systemd unit file and try again. This dont work in OpenVZ/Virtuozzo

**Comment by yoorshop** [comment]
We are on OpenVZ/Virtuozzo, but let try anyway

**Comment by yoorshop** [comment]
Thanks to not close issue within 3 minutes. I know we must pay for support, but most I report are always bugs, and I'm obliged to even poay to report a bug it seems now...

There is no file nginx.service in centos 7, even on dedicated servers centos7, this is nowhere : ExecStartPre=/usr/sbin/sysctl in any server

**Comment by AnoopAlias** [comment]
Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
This is from what tou pasted! . This is exactly why I closed down the forum. People are misusing it .I used to spend 4-5 hours daily for support which is not paid .Eventually I will end up with having to search for a day job and then XtendWeb project will have to close down
