### ISSUE TITLE
Connection refused to unix socket

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#193]
One of our servers is getting strange issue happening over and over with XtendWeb backends. I have seen it periodically with PHP and now with HHVM (I tried HHVM as the backed for a WordPress website to check if this will trigger the same error). Not sure if this error relates to your plugin or if it is a general server-level error, but maybe you could shed some light on where to look:

The error  **(Connection refused) while connecting to upstream**

This is the log extract, but it was showing same error for PHP earlier this week.

2017/04/09 17:09:43 [error] 851127#851127: *268343 connect() to unix:/home/[removed]/hhvm.sock failed (111: Connection refused) while connecting to upstream, client: [IP address removed], server: [URL removed], request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://unix:/home/[removed]/hhvm.sock:", host: "URL [removed]", referrer: "[URL removed]"

I saw the socket file existed at the time of this error and to resolve the problem the /attempt_autofix script had to be executed. Restarting ndeploy_backends did not help.

**Comment by AnoopAlias** [comment]
restarting ndeploy_backends will not restart hhvm as its managed by systemd .

you need to explicity do systemctl restart ndeploy_hhvm@user.service

where user = the cpanel username

111: Connection refused - Means nginx is unable to connect to that socket . The socket file may be present ; but there may be issues like the hhvm service has failed leaving socket open or some other issue with hhvm which you need to check in hhvm logs.
