### ISSUE TITLE
OCSP_basic_verify() failed while running nginx in proxy mode

### ISSUE THREAD

**Issue by roybj** [AnoopAlias/nDeploy#194]
Getting the following error while running xtendweb nginx in proxy mode 

OCSP_basic_verify() failed (SSL: error:27FFF065:OCSP routines:CRYPTO_internal:certificate verify error:Verify error:unable to get issuer certificate) while requesting certificate status, responder: gp.symcd.com, peer: 23.54.187.27:80, certificate: "/etc/nginx/ssl/example.com.crt"

Apache was working fine before xtendweb installation.

**Comment by AnoopAlias** [comment]
This happens and is not lethal. Just that the ocsp stapling data is not appended because of this error. You can ignore this error
