### ISSUE TITLE
Pagespeed does not work by default over HTTPS

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#196]
pagespeed.conf does not have an option 

pagespeed FetchHttps enable;

which is enabled in the latest pagespeed by default, however with no such line pagespeed does not work for SSL connections.

Adding this line immediately enables it.

Consider adding this line into default configuration.

**Comment by AnoopAlias** [comment]
https://modpagespeed.com/doc/https_support

*HTTPS fetching is built in and is enabled by default as of 1.10.33.0*

Since we are using 1.11.33.x version , this is already On . I don't see a point in explicitly turning it On.

Let me know if you don't see pagespeed optimized content in https://
