### ISSUE TITLE
Purely commercial extension?

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#198]
Ok, I am looking at the prefilled text here and finding myself nowhere. I have a question which does not qualify for commercial support, and it seems you have no community support anywhere, even in GitHub.

Is there a way to ask a question or seek for community support? A forum, a Q/A website?

Are you becoming a purely commercial product?

The question I have is how to have a default config for new account, for example:
PROXY to HTTPD with Microcache option,
or PHP 7.0 with Wordpress
or anything else.

Or maybe there is a way to map such default option to a cPanel package?

**Comment by AnoopAlias** [comment]
@ivrh XtendWeb is GPL and the product will be free. But I have decided to stop providing support for usage/installation to provide value to people who subscribe to paid support.

Your question's answer can be found in the documentation - https://xtendweb.gnusys.net/XtendWeb_Administration.html

**Comment by AnoopAlias** [comment]
more specifically - https://xtendweb.gnusys.net/XtendWeb_Administration.html#managing-default-server-settings

**Comment by ivangrynenko** [comment]
Thank you for the update
