### ISSUE TITLE
redirect to SSL breaks cPanel's AutoSSL

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#199]
All domains that have the "redirect to SSL" option in XtendWeb plugin management console On, fail AutoSSL renewal. 

I have been observing this issue for a while, now decided to report it.

The error reported is that SSL validation script requires only 1 redirect, but more that 1 redirect occurred.

Not sure about the solution here, but at least a warning description would be good to have under this option, to avoid enabling it if AutoSSL is on for the domain.

See this screenshot:
https://www.evernote.com/l/AKHn0m5hmSdAC6KBaTaZbIbYECGbXjo5zNs

**Comment by AnoopAlias** [comment]
@ivrh - What autoSSL provider are you using?
https://forums.cpanel.net/threads/autossl-and-http-redirects.567801/

As per this redirecting to SSL should not cause errors. But external redirects may cause issue. 

I think the templates have the only exclusion for LentsEncrypt AutoSSL. So if you confirm the provider ,I can check this further.

**Comment by ivangrynenko** [comment]
Using default cPanel/Comodo provider.

For now trying to use HSTS instead of `redirect to SSL` option - should achieve the same outcome by instructing the browser to use SSL version of the page without the redirect. Will see how this works next time the renewal is due.

**Comment by AnoopAlias** [comment]
@ivrh - Please try upgrade to nDeploy-4.3-4 and run autofix.sh scrit to rebuild configs.

Let me know if this helps
