### ISSUE TITLE
nginx: [emerg]

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#200]
nginx: [emerg] unknown directive "32}\.txt$"" in /etc/nginx/sites-enabled

**Comment by weltonwe** [comment]
# Comodo
location ~* ^/[A-F0-9]{32}\.txt$" {
allow all;
error

**Comment by vacancy12345** [comment]
I saw the same error in my last setup. Nginx not starting.
version nDeploy-4.3-4.el6.noarch - nginx-nDeploy-1.12.0-1.el6.x86_64


> Attempting to regenerate all nginx conf
ConfGen:: username1
ConfGen:: username2
nginx: [emerg] unknown directive "32}\.txt$"" in /etc/nginx/sites-enabled/destek.username2.com.conf:45


> httpd started successfully.
nginx: [emerg] unknown directive "32}\.txt$"" in /etc/nginx/sites-enabled/destek.username2.com.conf:45
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by AnoopAlias** [comment]
Hi ..Please comment out the comodo line for time being in /opt/nDeploy/conf/server.j2 at 2 locations and run attempt_autofix.sh.

I will provide an updated rpm in an hour max.

Thanks.

**Comment by AnoopAlias** [comment]
@weltonwe @vacancy12345  - The updated rpm is up .The error was caused by a typo in the server.j2 .Please do

yum --enablerepo=ndeploy clean all
yum --enablerepo=ndeploy upgrade

Thanks.
