### ISSUE TITLE
php_secure_backend_add() takes at least 4 arguments (3 given)

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#201]
I just updated to:
 nDeploy                                                        noarch                            4.3-5.el7                                 ndeploy                            128 k
 nginx-nDeploy                                                  x86_64                            1.12.0-1.el7                              ndeploy                            5.8 M
 nginx-nDeploy-module-brotli                                    x86_64                            1.12.0-1.el7                              ndeploy                            1.2 M
 nginx-nDeploy-module-echo                                      x86_64                            1.12.0-1.el7                              ndeploy                            339 k
 nginx-nDeploy-module-geoip                                     x86_64                            1.12.0-1.el7                              ndeploy                             64 k
 nginx-nDeploy-module-naxsi                                     x86_64                            1.12.0-1.el7                              ndeploy                            489 k
 nginx-nDeploy-module-pagespeed                                 x86_64                            1.12.0-1.el7                              ndeploy                             33 M
 nginx-nDeploy-module-redis                                     x86_64                            1.12.0-1.el7                              ndeploy                             61 k
 nginx-nDeploy-module-redis2                                    x86_64                            1.12.0-1.el7                              ndeploy                            143 k
 nginx-nDeploy-module-set_misc                                  x86_64                            1.12.0-1.el7                              ndeploy                            378 k
 nginx-nDeploy-module-srcache_filter                            x86_64                            1.12.0-1.el7                              ndeploy                            208 k

Now we get the following error:

`
/opt/nDeploy/scripts/generate_config.py username
Job for CPANELPHP56@username.socket failed. See "systemctl status CPANELPHP56@username.socket" and "journalctl -xe" for details.
Traceback (most recent call last):
  File "/opt/nDeploy/scripts/generate_config.py", line 610, in <module>
    nginx_confgen(is_suspended, clusterenabled, *cluster_serverlist, configuser=cpaneluser, configdomain=main_domain, maindomain=main_domain)  # Generate conf for main domain
  File "/opt/nDeploy/scripts/generate_config.py", line 521, in nginx_confgen
    php_secure_backend_add(kwargs.get('configuser'), domain_home, backend_version)
TypeError: php_secure_backend_add() takes at least 4 arguments (3 given)
`

I have rebuilt the user data and cache just in case, but the problem still persists.

**Comment by AnoopAlias** [comment]
@atxcowboy  - Please try

yum --enablerepo=ndeploy clean all
yum --enablerepo=ndeploy upgrade

and you should be upgraded to 4.3.6 version

Let me know if there is any more issues.

**Comment by atxcowboy** [comment]
Perfect I had missed the clean all.
