### ISSUE TITLE
Adding subdir apps fails

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#202]
Client reports WordPress install in subdir doesn't work since XtendWeb upgrade.

When trying to configure a Subdir app (Backend version CPANELPHP), the following happens:

type 'exceptions.AttributeError'>	Python 2.7.5: /usr/bin/python
Fri Apr 28 11:55:49 2017
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /usr/local/cpanel/base/frontend/paper_lantern/nDeploy_cp/subdir_save_app_settings.live.py in ()
     81             yaml_parsed_profileyaml = yaml.safe_load(profileyaml_data_stream)
     82         subdir_apps_dict = yaml_parsed_profileyaml.get('subdir_apps')
=>   83         if thesubdir in subdir_apps_dict.keys():
     84             the_subdir_dict = subdir_apps_dict.get(thesubdir)
     85         else:
thesubdir = 'wordpress', subdir_apps_dict = None, subdir_apps_dict.keys undefined
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'keys' 
      args = ("'NoneType' object has no attribute 'keys'",) 
      message = "'NoneType' object has no attribute 'keys'"

**Comment by AnoopAlias** [comment]
Are you trying to add a sub dir or edit existing one?. looks like you are trying to edit /wordpress ?

Ensure the domain data YAML has the sub dir section intact. I just tested adding a sub dir on a local install (latest version ) and don't see any issue.

**Comment by atxcowboy** [comment]
It turns out subdir_apps: {} was missing in /opt/nDeploy/domain-data/customerdomain.tld
Most errors seem to come from missing keys in there. I guess I’ll try to write a script to auto populate missing keys.

Thanks for your fast turnaround time.

Last year at WorldHosting Days I talked to the cPanel guys and showcased ndeploy to them. :)

Ciao
        Sascha

**Comment by AnoopAlias** [comment]
hmm not sure why it is missing. I haven't seen this error in the local test machines. The key gets added when a user adds a subir from the UI .

Thanks for showcasing the product. Please check out the fully automated multi-datacenter clustering setup too https://xtendweb.gnusys.net/docs/installation_cluster.html .Its a new addition in the 4.3.x version. Also do support the project by subscribing to a sysadmin service offered by gnusys .Subscribing also gives you a listing at the partner page https://xtendweb.gnusys.net/docs/Partner_webhosts.html

Have a good day.
