### ISSUE TITLE
syntax error on xtendweb_mysql_grants.sql

### ISSUE THREAD

**Issue by ghost** [AnoopAlias/nDeploy#204]
please update your source of xtendweb_mysql_grants.sql, because I am using mariaDB.

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 

please fix this line, because I have check
`CREATE USER 'maxscale'@'blabla' IDENTIFIED BY password;
`
but line must be

`CREATE USER 'maxscale'@'blabla' IDENTIFIED BY 'password';`

**Comment by AnoopAlias** [comment]
You need to enable the single quoted password in /root/.my.cnf

The jinja2 will substitute the quotes too. 

Its given as a Tip in https://xtendweb.gnusys.net/docs/installation_cluster.html#xtendweb-cluster-setup

**Comment by ghost** [comment]
okay, I have solved about this. but why you have update db replica on cpanel?

```
[ndeploydbslave] # This section has the DB slave .Only one entry should be there
slave1.example.com ansible_port=22 server_id=2 webserver=nginx
```

before I have following your topology with **standalone database server**

and now I have get too much error because mysql socket

**Comment by AnoopAlias** [comment]
standalone database server= single point of failure
Please subscribe to a paid support plan at https://support.gnusys.net/order.php if you need assistance.

By subscribing you will be supporting the XtendWeb development too.

Thanks.

**Comment by ghost** [comment]
lol, I mean I have 2 standalone database server with master-master replication
now all the configure is error because new update.

so bad if you redirect to me to using assistance feature, so we can't deploy or published your apps to my country.

thx

**Comment by AnoopAlias** [comment]
You can use the app..but app evolves and  as an open source app ..its developer can't provide free upgrade help. So you have 3choice . 1. Stay on old version and dont upgrade 2. Learn what is changed and do it on your own.  3. pay for paid support.

**Comment by ghost** [comment]
stay on old version but your repo say must be upgrade? how to downgrade?

**Comment by AnoopAlias** [comment]
the repo is disabled. you have to manually upgrade if you did.

There is no downgrade path. However, you don't need to rerun the playbook and can enjoy new nDeploy and Nginx .If you have run the playbook and is stuck. I am sorry its too much involved now!

**Comment by ghost** [comment]
okay thanks
