### ISSUE TITLE
maxscale error, mariadb error

### ISSUE THREAD

**Issue by pangeran1995** [AnoopAlias/nDeploy#206]
Good night

I have followed the tutorials that are on the website,
I use centos 7
And I'm having constraints on the maxscale part
in the

TASK [maxscale_master : Start MaxScale] ***************************************************************************************************************
fatal: [aaaaa.zzzzz.com]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service maxscale: Job for maxscale.service failed because the control process exited with error code. See \"systemctl status maxscale.service\" and \"journalctl -xe\" for details.\n"}

systemctl status maxscale.service

May 05 12:03:32 aaaa.zzzz.com maxscale[12799]: XtendWeb: Inadequate user permissions for service. Service not started.
May 05 12:03:32 aaaa.zzzz.com maxscale[12799]: Failed to start service 'XtendWeb'.
May 05 12:03:32 aaaa.zzzz.com maxscale[12799]: Loaded module maxscaled: V2.0.0 from /usr/lib64/maxscale/libmaxscaled.so
May 05 12:03:32 aaaa.zzzz.com maxscale[12799]: Listening connections at /tmp/maxadmin.sock with protocol MaxScale Admin
May 05 12:03:32 aaaa.zzzz.com maxscale[12799]: Failed to start all MaxScale services. Exiting.
May 05 12:03:32 aaaa.zzzz.com systemd[1]: maxscale.service: control process exited, code=exited status=3
May 05 12:03:32 aaaa.zzzz.com maxscale[12797]: Shutting down MaxScale
May 05 12:03:32 aaaa.zzzz.com systemd[1]: Failed to start MariaDB MaxScale Database Proxy.
May 05 12:03:32 aaaa.zzzz.com systemd[1]: Unit maxscale.service entered failed state.
May 05 12:03:32 aaaa.zzzz.com systemd[1]: maxscale.service failed.

thanks

**Comment by AnoopAlias** [comment]
Its a maxscale issue. You need to troubleshoot it relative to your environment. 

You can opt for commercial support if you want me to check by logging into your system.
