### ISSUE TITLE
nginx stopped (ssl error)

### ISSUE THREAD

**Issue by vacancy12345** [AnoopAlias/nDeploy#207]
Nginx has stopped working on its own today.

I use the monit automatic start, but the nginx configuration shows an error.

`[root@sunucu ~]# service nginx restart

nginx: [emerg] BIO_new_file("/var/cpanel/ssl/installed/certs/fb_ozdogan_org_f16bc_a2469_1522702365_ecd5372a5661adeed1999349b058506b.crt") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/var/cpanel/ssl/installed/certs/fb_username_org_f16bc_a2469_1522702365_ecd5372a5661adeed1999349b058506b.crt', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed`

**Comment by AnoopAlias** [comment]
run

/opt/nDeploy/scripts/attempt_autofix.sh

Issue is random errors due to #126 . No upstream hook for SSL

**Comment by vacancy12345** [comment]
Hi anoop.

Can it work for a temporary solution? I started this subject.

https://forums.cpanel.net/threads/autossl-renew-check-cron-time.603243

**Comment by AnoopAlias** [comment]
The latest version of XtendWeb already has an hourly cron (/etc/con.hourly/xtendweb) that automatically corrects any configuration issues. Please try upgrading to the latest version and let me know if you still get any errors.

**Comment by sincerbex** [comment]
i have the same problem but if i run 
`/opt/nDeploy/scripts/attempt_autofix.sh`

result:

`Attempting to regenerate all nginx conf
ConfGen:: b****k
ConfGen:: co******ca
ConfGen:: e****d
ConfGen:: e**k
ConfGen:: f***t
ConfGen:: f**a
ConfGen:: h***k
ConfGen:: i**a
ConfGen:: i****a
ConfGen:: m**i

 Attempting to regenerate  nginx default conf
 !!! Removing conflicting mod_evasive ea-apache24-mod_evasive ea-apache24-mod_ruid2 ea-apache24-mod_http2 rpm
Plugin abilitati:fastestmirror, universal-hooks
Nessuna corrispondenza per l'argomento: ea-apache24-mod_ruid2
Nessuna corrispondenza per l'argomento: ea-apache24-mod_http2
Nessuna corrispondenza per l'argomento: ea-apache24-mod_evasive
Nessuna corrispondenza per l'argomento: mod_evasive
Nessun pacchetto marcato per la rimozione
Plugin abilitati:fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 31.22.112.31
 * cpanel-addons-production-feed: 31.22.112.31
 * cpanel-plugins: 31.22.112.31
 * base: pkg.adfinis.com
 * epel: pkg.adfinis.com
 * extras: pkg.adfinis.com
 * updates: pkg.adfinis.com
Il pacchetto ea-apache24-mod_remoteip-2.4.53-2.2.1.cpanel.x86_64 è già installato e aggiornato all'ultima versione
Niente da fare
Redirecting to /bin/systemctl reload nginx.service
 Attempting to restart ndeploy_watcher daemon
`
 but the problem persists, if i start nginx on slave:

`nginx -t
nginx: [emerg] cannot load certificate "/var/cpanel/ssl/cpanel/mycpanel.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/cpanel/mycpanel.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed`
How can I solve the problem?

**Comment by AnoopAlias** [comment]
@sincerbex  this is due to fact that there is no AutoSSL cert for the hostname issued. The file /var/cpanel/ssl/cpanel/mycpanel.pem doesn't exist

Please run /opt/nDeploy/scripts/generate_default_vhost_config.py 

and see if that fixes the error

If not Just copy /var/cpanel/ssl/cpanel/cpanel.pem over to /var/cpanel/ssl/cpanel/mycpanel.pem  and that should fix it!

**Comment by sincerbex** [comment]
@AnoopAlias 
i run on master
`/opt/nDeploy/scripts/generate_default_vhost_config.py`
the output is blank
now if i run on slave 
`nginx -t`
i have this error
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] bind() to xx.xx.xx.xx:80 failed (99: Cannot assign requested address)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
the slave server is under nat whit relative properly opened
xx.xx.xx.xx his ip address that makes me see the error is the public, but there should be the ip address of the machine?
is there a script to reconfigure?

**Comment by AnoopAlias** [comment]
Please open a ticket from your registered email address and you will get assistance. Please use the GitHub bug track only for code related issues
