### ISSUE TITLE
/opt/nDeploy/scripts/generate_config.py Error

### ISSUE THREAD

**Issue by pangeran1995** [AnoopAlias/nDeploy#208]
I tried to use /opt/nDeploy/scripts/attempt_autofix.sh to find the solution, but error in cli

Traceback (most recent call last):
  File "/opt/nDeploy/scripts/generate_config.py", line 610, in <module>
    nginx_confgen(is_suspended, clusterenabled, *cluster_serverlist, configuser=cpaneluser, configdomain=main_domain, maindomain=main_domain)  # Generate conf for main domain
  File "/opt/nDeploy/scripts/generate_config.py", line 293, in nginx_confgen
    backend_category = yaml_parsed_domain_data.get('backend_category', None)
AttributeError: 'NoneType' object has no attribute 'get'
 Attempting to restart all backend Application servers
 The following PHP-FPM master process has started
 Attempting to restart ndeploy_watcher daemon

And for the Cpanel user error

A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /usr/local/cpanel/base/frontend/paper_lantern/nDeploy_cp/app_settings.live.py in ()
     96             yaml_parsed_profileyaml = yaml.safe_load(profileyaml_data_stream)
     97         # App settings
=>   98         backend_category = yaml_parsed_profileyaml.get('backend_category')
     99         backend_version = yaml_parsed_profileyaml.get('backend_version')
    100         backend_path = yaml_parsed_profileyaml.get('backend_path')
backend_category undefined, yaml_parsed_profileyaml = None, yaml_parsed_profileyaml.get undefined
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get' 
      args = ("'NoneType' object has no attribute 'get'",) 
      message = "'NoneType' object has no attribute 'get'"

**Comment by AnoopAlias** [comment]
there is no domain-data file in /opt/nDeploy/domain-data/

**Comment by pangeran1995** [comment]
I see the domain-data list
