### ISSUE TITLE
WordPress template q=$uri causes problems

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#209]
The XtendWeb Wordpress templates feature the following syntax:
`try_files $uri $uri/ /index.php?q=$uri&$args;`

The official [WordPress recommendation for nginX](https://codex.wordpress.org/Nginx) however says:
`try_files $uri $uri/ /index.php?$args ;`

(notice the extra q=$uri with XtendWeb).

Adding the extra q query string parameter causes problems with some [plugins](https://wordpress.org/support/topic/too-many-redirect-with-qtranslate-x/).

Can this be removed or do you expect other problems by removing this?

**Comment by AnoopAlias** [comment]
I have updated the template. Please upgrade rpm and run attempt_autofix to update configs.
