### ISSUE TITLE
TASK [mariadb_master : set_fact]  fails

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#210]
I'm attempting to migrate a 3 node (2 xtendweb, 1 mariadb only) ndeploy cluster to xtendweb.

The dnsonly slave has been reinstalled with a fresh OS template, the master node has been upgraded by uninstalling previous ndeploy and reinstalling xtendweb. xtenweb is running without problems. So I'm following the [cluster installation guide](https://xtendweb.gnusys.net/docs/installation_cluster.html?highlight=mysql#xtendweb-cluster-requirements).

When running `ansible-playbook -i ./hosts cluster.yml` on the master as per step 7 in the guide, it produces the following error:

```
TASK [mariadb_master : set_fact] *********************************************************************************************************************************************************************************************************
fatal: [hostname_of_master]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'File'\n\nThe error appears to have been in '/opt/nDeploy/conf/nDeploy-cluster/roles/mariadb_master/tasks/main.yml': line 85, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
```

Lines 85 onwards are:
```
- set_fact:
    masterlog: "{{ masterrepl.File }}"
    masterpos: "{{ masterrepl.Position }}"
```

**Comment by AnoopAlias** [comment]
did any other task fail previously? The task is getting the variables from master status and registering itself as a fact. My best guess is that SHOW MASTER STATUS; may not be working on MariaDB on the master . You can setup a fresh cluster and migrate the accounts over using cPanel migration tool which might be easier.
