### ISSUE TITLE
Plugin ndeploy issue

### ISSUE THREAD

**Issue by tnr87** [AnoopAlias/nDeploy#213]
I installed ndeploy software to cpanel
screencast.com/t/DhpyYELhv
when enter inside it:
screencast.com/t/asnFvVWCns94
i updated extension with new version
new version activated but it didnt deleted on server so it didnt removed completely

now server running on litespeed
related extention couldnt deleted on server because of this apache not running.
How can i remove related extension, completely?
Wheres the installed extension files path on c panel?
I removed ./opt/ndeploy files from this location completely but i still see this software on c panel

**Comment by AnoopAlias** [comment]
XtendWeb software is all rpm. You should use yum/rpm to remove plugin. 

Please check docs.

You can opt for a commercial support plan if you need me to login and fix this for you.
