### ISSUE TITLE
/opt/nDeploy/scripts/attempt_autofix.sh

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#214]
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: wonderho
/opt/nDeploy/scripts/generate_config.py: line 7: syntax error near unexpected token `newline'
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: wrhosped
/opt/nDeploy/scripts/generate_config.py: line 7: syntax error near unexpected token `newline'
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: wwwfixsign
/opt/nDeploy/scripts/generate_config.py: line 7: syntax error near unexpected token `newline'
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: wxsdacom
/opt/nDeploy/scripts/generate_config.py: line 7: syntax error near unexpected token `newline'
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: xbxtqzoz
/opt/nDeploy/scripts/generate_config.py: line 7: syntax error near unexpected token `newline'
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: xhabboin
/opt/nDeploy/scripts/generate_config.py: line 7: syntax error near unexpected token `newline'
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: yukyes
/opt/nDeploy/scripts/generate_config.py: line 7: syntax error near unexpected token `newline'
/opt/nDeploy/scripts/generate_config.py: line 7: `<!DOCTYPE html>'
ConfGen:: zapatapl

**Comment by AnoopAlias** [comment]
Whats line 7 in generate_config.py?

I think the file is corrupt or locally modified
