### ISSUE TITLE
How to be notified of new release

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#22]
Hello,

Without visiting https://support.sysally.net/projects/ndeploy/news is there a way to be notified of the need to run the update command when a new release is made?

Thanks!

**Comment by AnoopAlias** [comment]
1.You can enable the repo by explicitly stating enabled=1 which will make changes automatic .It should be fine . 

2. The news page has atom feed which you can use with something like http://www.feednotifier.com/
