### ISSUE TITLE
Research https://github.com/kyprizel/testcookie-nginx-module integration

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#220]
Integrate test-cookie module for robot mitigation and l7 ddos mitigation

**Comment by hostingfuze** [comment]
I've implemented this for over a month and it works with the latest version of nginx!
demo : http://www.romcatel.ro

**Comment by AnoopAlias** [comment]
Ok cool.Expect this in the next version.

**Comment by hostingfuze** [comment]
But I did not succeed on ipv6
