### ISSUE TITLE
systemctl restart nginx.service

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#227]
systemctl status nginx.service
* nginx.service - nginx-nDeploy - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-06-16 15:11:28 -03; 8s ago
     Docs: http://nginx.org/en/docs/
  Process: 4926 ExecStartPre=/usr/sbin/sysctl -w net.core.netdev_max_backlog=16384 (code=exited, status=255)
  Process: 4923 ExecStartPre=/usr/sbin/sysctl -w net.core.somaxconn=16384 (code=exited, status=0/SUCCESS)

Jun 16 15:11:28 network1 systemd[1]: Starting nginx-nDeploy - high performa.....
Jun 16 15:11:28 network1 sysctl[4923]: net.core.somaxconn = 16384
Jun 16 15:11:28 network1 sysctl[4926]: sysctl: permission denied on key 'ne...g'
Jun 16 15:11:28 network1 systemd[1]: nginx.service: control process exited,...55
Jun 16 15:11:28 network1 systemd[1]: Failed to start nginx-nDeploy - high p...r.
Jun 16 15:11:28 network1 systemd[1]: Unit nginx.service entered failed state.
Jun 16 15:11:28 network1 systemd[1]: nginx.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by AnoopAlias** [comment]
cp -p /usr/lib/systemd/system/nginx.service /etc/systemd/system/
edit /etc/systemd/system/nginx.service and comment out the ExecStartPre lines
systemctl daemon-reload
systemctl restart nginx

**Comment by weltonwe** [comment]
[root@network1 ~]# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
[root@network1 ~]# systemctl restart nginx
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
[root@network1 ~]# systemctl status nginx.service
* nginx.service - nginx-nDeploy - high performance web server
   Loaded: loaded (/etc/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-06-17 00:05:51 -03; 9s ago
     Docs: http://nginx.org/en/docs/
  Process: 6773 ExecStartPre=/usr/sbin/sysctl -w net.core.netdev_max_backlog=16384 (code=exited, status=255)
  Process: 6770 ExecStartPre=/usr/sbin/sysctl -w net.core.somaxconn=16384 (code=exited, status=0/SUCCESS)

Jun 17 00:05:51 network1 systemd[1]: Starting nginx-nDeploy - high performance web server...
Jun 17 00:05:51 network1 sysctl[6770]: net.core.somaxconn = 16384
Jun 17 00:05:51 network1 sysctl[6773]: sysctl: permission denied on key 'net.core.netdev_max_backlog'
Jun 17 00:05:51 network1 systemd[1]: nginx.service: control process exited, code=exited status=255
Jun 17 00:05:51 network1 systemd[1]: Failed to start nginx-nDeploy - high performance web server.
Jun 17 00:05:51 network1 systemd[1]: Unit nginx.service entered failed state.
Jun 17 00:05:51 network1 systemd[1]: nginx.service failed.
[root@network1 ~]#
