### ISSUE TITLE
Magento template stripping GET params

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#230]
In the 5003.j2 Magento template the pagination is not working domains and shows the first page only. All of the pagination controls (changing the number per page, changing from "grid" to "list", etc) are similarly broken.

One of our customers was nice enough to do a little digging (print_r($_GET) in index.php) and noticed that it was empty. All GET params are being stripped. To resolve this issue, he changed
try_files $uri $uri/ /index.php;

to

try_files $uri $uri/ /index.php?$query_string;

**Comment by AnoopAlias** [comment]
Thanks for the heads up. fixed template
