### ISSUE TITLE
Feature request: Nginx include for custom configuration

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#232]
Consider adding Nginx includes for custom configuration.

At the moment you include file with the pattern of `{domainname}.manualconfig*` however, it gets removed upon `attempt_autofix` is run. It would be great to have the ability to add customisations, similar to cPanel Apache includes does. Even if `{domainname}.manualconfig*` stays permanently, this will be sufficient.

**Comment by AnoopAlias** [comment]
@ivrh - the file name ending with .manualconfig should not be removed in attempt_autofix . Infact attempt_autofix does not remove any files..it just regenerate(overwrite) .conf and .include file 

eg: in /etc/nginx/sites-enabled/autom8n.net.conf  I have
###
include /etc/nginx/sites-enabled/autom8n.net.manualconfig*;
#####

So we can go on including any number of files like
/etc/nginx/sites-enabled/autom8n.net.manualconfig
/etc/nginx/sites-enabled/autom8n.net.manualconfig_xyz
/etc/nginx/sites-enabled/autom8n.net.manualconfig.mycustomrewrites
/etc/nginx/sites-enabled/autom8n.net.manualconfig123
etc
and all these files will be included .

However, note that using a template is much better as templates can be activated for just one user and its reusable and users can change configuration by choosing a different template . If you add manualconfig include file...the file gets included always and users have no way to remove the config than contacting the server admin.

I did test this on my local setup and attempt_autofix did not remove! the file. Not sure why its being removed in your case. If you feel this is a bug and want me to have a look ,send server creds etc to ops@gnusys.net 

Thanks.
