### ISSUE TITLE
Cpanel service SSL no longer valid.

### ISSUE THREAD

**Issue by hiddenmagic** [AnoopAlias/nDeploy#234]
Having a great experience now that everything is setup and installed. Very fast response times, and nginx is great.

However, immediately after install all of our cpanel service subdomains: cpanel.mydomain.com webmail.mydomain,com, etc are all invalid, and using the SSL for the main server.

Subdomains created by users in Cpanel are unaffected. Any thoughts at all?

**Comment by AnoopAlias** [comment]
The cpanel. , whm. etc subdomains are not included in the config .You can however use
domain.com/cpanel domain.com/whm, domain.com/webmail etc 

Let me know if this is a must have feature and I would look into including the config.

**Comment by hiddenmagic** [comment]
Hey, thanks for a quick and honest response.

Well, it's what customers have been using for a long time, and changing ANYTHING can send them into a rage for sure. 

Also, our business processes, email templates that go out print material, etc. They all reference these subdomains. Yes, I would say it's important enough for you to look into. However, even if you don't look into this for me, it doesn't mean we're uninstalling. We'll just be forced to adapt.

The cut in CPU load, and speed provided by your plugin is far more important than the customer service issues we're experiencing. Also, we would have known this had we tested it fully before launch!

Thanks for a great extension to WHM & Cpanel!

**Comment by AnoopAlias** [comment]
@hiddenmagic . Thanks. I will surely look into adding this at priority.

**Comment by AnoopAlias** [comment]
Just fixed this and once I test this on my test server and found to be ok, it will be available in the next RPM release
