### ISSUE TITLE
Downloading packages

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/nDeploy#236]
Tamanho total do download: 6.0 M
Tamanho depois de instalado: 14 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
nginx-nDeploy-1.12.0-2.el7.x86 FAILED
https://autom8n.com/CentOS/7/x86_64/nginx-nDeploy-1.12.0-2.el7.x86_64.rpm: [Errno 14] HTTPS Error 403 - Forbidden
Tentando outro espelho.
nDeploy-4.3-18.el7.noarch.rpm  FAILED
https://autom8n.com/CentOS/7/x86_64/nDeploy-4.3-18.el7.noarch.rpm: [Errno 14] HTTPS Error 403 - Forbidden
Tentando outro espelho.

**Comment by AnoopAlias** [comment]
https://plus.google.com/u/3/b/106986716786203781622/106986716786203781622/posts/jgHd16n1jnp
