### ISSUE TITLE
CentOS 6 update fails

### ISSUE THREAD

**Issue by ivangrynenko** [AnoopAlias/nDeploy#238]
In CentOS 6 server, running yum update returns the error:

```
https://gnusys.net/CentOS/6/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

```

Is this something that you stopped supporting recently?

**Comment by AnoopAlias** [comment]
@ivrh  Xtendweb has changed its monetizing model to that of RHEL. The software is free but access to the yum channel needs a license 

https://plus.google.com/u/0/106986716786203781622/posts/jgHd16n1jnp
