### ISSUE TITLE
Domain continually forwards to https when it's not enabled

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#24]
@AnoopAlias -- Can you please check on a site on my server (user dockbiz) and see why it's forcing to go to https://domainname instead of http://domainname?

I'm attempting to install https://github.com/snipe/snipe-it

**Comment by AnoopAlias** [comment]
Hello Brian,

Please send in the server login creds to support[at]sysally[dot]net or add the pub-key I had already given you and update me the details. You can also check /etc/nginx/sites-enabled/DOMAIN.include and see if its doing a redirect from nginx .

Thank you,
Anoop
