### ISSUE TITLE
Using nDeploy with EasyApache4 

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#25]
Hello,

Can you please advise as to how to go about using EasyApache4 with nDeploy? Can we go back to using system installed PHP versions?

**Comment by brianjking** [comment]
Specifically one area I'm really in need of information on is if I'm using the PHP-FPM Handler from nDeploy how does this work once I upgrade to EasyApache4?

**Comment by AnoopAlias** [comment]
nDeploy is tested with EA4 and it was found to be working perfect . The additional php-fpm from cPanel as well as all PHP versions from their muti-php etc can be readily used with nDeploy. You just need to register them as a backend in nDeploy with an appropriate unique name.
