### ISSUE TITLE
Using Rocket-Nginx w/ nDeploy 

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#26]
Hi Anoop,

I'm attempting to use Rocket-Nginx for a few of my sites (https://github.com/maximejobin/rocket-nginx) and am having trouble with getting it setup.

```

Then, in your configuration file, you must include the configuration. If your websites configurations are in /etc/nginx/sites-available, you need to alter your configuration:

server {
  ...

  # Rocket-Nginx configuration
  include rocket-nginx/rocket-nginx.conf;

  ...
}

```

Where would I put this for it to apply to a single domain using NGINX via nDeploy?

**Comment by AnoopAlias** [comment]
You simply need to use the nDeploy plugin interface and 
1. Set AUTO mode and select PHP and template "wordpress or drupal"
2. Again edit the domain in MANUAL mode and remove all locations except the php one and paste everything in the rocket-nginx config above the php location.

Thats it!

**Comment by brianjking** [comment]
@AnoopAlias Why not use the High Performance Nginx Configuration?

**Comment by AnoopAlias** [comment]
@brianjking The config template is irrelevant and you can use any php one ..the intention is to generate the .php location required for php processing which works in all php templates.

But checking the configs in rocket-nginx ; I dont see a setting for location / {} . Confirm with the developer that we should use the normal try_files in wordpress / along with the rocket-nginx setting in which case you have to delete all location except / and php and include the other configs from rocket-nginx alongside in manual edit.
