### ISSUE TITLE
Mod_RemoteIP with EasyApache4

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#27]
Hello,

As per (https://support.sysally.net/projects/ndeploy/wiki/Mod_remoteip_) I have installed Mod_RemoteIP via the provided Yum command and when I execute 

````vim /etc/apache2/conf.modules.d/360_mod_remoteip.conf```` it has the following lines in it by default:

````
# Enable mod_remoteip
LoadModule remoteip_module modules/mod_remoteip.so
````

* _I believe you're stating that I need to add the lines below to this file with my Servers IP address, correct?_  

* _What if I have multiple IPs on my server?_

RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy x.x.x.x/24 #substitute x.x.x.x with yout IP address

Thanks!

**Comment by AnoopAlias** [comment]
@brianjking - Yes correct . You have to add all your IP's in the RemoteIPTrustedProxy one per line.

ie

RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy x.x.x.x/32
RemoteIPTrustedProxy y.y.y.y/32
..
etc

**Comment by brianjking** [comment]
@AnoopAlias How can I add this remoteIP module to EasyApache4 by default so that each time I re-compile for an update I do not have to execute these commands and add the details to the above 360_mod_remoteip.conf file?

All PHP Options + OpCache is the EasyApache4 build I'm using.

**Comment by AnoopAlias** [comment]
In EasyApache4 you will never recompile. You have to place that setting in a include file that rpm upgrade wont overwrite.
