### ISSUE TITLE
High memory consumption while using ModSecurity 

### ISSUE THREAD

**Issue by TaiSHiNet** [AnoopAlias/nDeploy#284]
When using `nginx-nDeploy-module-modsecurity` memory jumps from 0.3% per nginx process (over an 8GB total RAM) to 13%~ish at start, and 23%~ish after a few hours running.
I've read over at https://github.com/SpiderLabs/ModSecurity-nginx/issues/29#issuecomment-284819098 that it might be ModSec version
I've tried doing a package upgrade from nDeploy repo

Until this is fixed I've turned off modsec, given it implodes my server every now and then

**Comment by TaiSHiNet** [comment]
Seems it's not the first time this happens heh :P 
https://github.com/SpiderLabs/ModSecurity-nginx/issues/45#issuecomment-304295304

**Comment by AnoopAlias** [comment]
@TaiSHiNet  - yes modsec_v3 is still beta and plagued by various issues. memory issue and unable to start with a large number of vhost is some I am aware of. Hopefully, all this pass while the project mature.

**Comment by TaiSHiNet** [comment]
Please update this if you're aware of any fixes or resolutions, for now I'll keep it disabled.
Thanks!

**Comment by AnoopAlias** [comment]
@TaiSHiNet - no workarounds that I know of yet. You can directly open the ticket in SpiderLabs/ModSecurity-nginx as this is a software issue in the project itself.
