### ISSUE TITLE
integrate geodns and python-dnslb

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#293]
https://github.com/abh/geodns
https://github.com/leifj/python-dnslb

As a replacement for cPanel Bind in the cluster. 

This could be done instead of #264 as CloudFlare traffic cost is prohibitive 
and as a closure to #137

(Implementation target Q1 2018)

**Comment by yoorshop** [comment]
keep up the good job, i need this ASAP

**Comment by AnoopAlias** [comment]
This is complete and as of now we support A , MX , NS, TXT and CNAME type records. 
More can be added on a need-to-do basis
The health check part is also done with basic check for http response below 400 code.
