### ISSUE TITLE
Locking xtendweb setting on account

### ISSUE THREAD

**Issue by copernic2006** [AnoopAlias/nDeploy#311]
Hi Anoop,
Now that we have the possibility to configure packs with different configurations of Nginx, it would be desirable to have the functionality to lock certain parameters in order not to allow end customers to change certain functionality that could affect the operation of his account .

**Comment by AnoopAlias** [comment]
@copernic2006 This feature is implemented and available in nDeploy-4.4-19+

Please upgrade your RPM .

You will be able to lock app-server and security-seting for a cPanel PKG from the WHM XtendWeb map-package-to-setting section
the 'settings_lock' feature enabled/disabled
