### ISSUE TITLE
Cluster setup : need Mysql read scalability

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#314]
This avoid issues with CMS like prestashop... and keep an overall maximal performance in cluster network, even more on  long distance where loading speed is killed...

Keep write at master only for obvious reasons of data integrity

**Comment by AnoopAlias** [comment]
This would need Master/Slave replication and integration of https://github.com/signal18/replication-manager

**Comment by yoorshop** [comment]
with such feature, and geodns, XtendWeb could become a professionnal, and reknown solution in HA solutions
It's time for higher horizons...

**Comment by AnoopAlias** [comment]
Fixed
