### ISSUE TITLE
Cluster nginx conf issue with slave

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#319]
By a mistake at nginx conf in master in ndeploy_cluster.yaml (links between IPs of master and slave... ), we had set with a wrong IP for slave...

We found that slave nginx was not working, and thus websites could not load

We corrected correct IP, and then regen conf at master, we observed that these new conf were not propagated to slave, we did it manually, and made a nginx restart

Events from master to slave for nginx conf when nginx conf is wrong on slave are not propagated it seems

**Comment by yoorshop** [comment]
Issue is well confirmed.

Even with correct IP changes in link with content of ndeploy_cluster.yaml.

config is not synced to slave + nginx reload

**Comment by yoorshop** [comment]
Anoop said that it was due in my case to hostname which was changed to short version by openvz node, and csync is sensible to that....

**Comment by AnoopAlias** [comment]
The issue caused by hostname being different than set up by ansible in csync2 config.
