### ISSUE TITLE
Title enduser cpanel

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#329]
Please remove 
NGINX CLUSTER CONTROL
by
Xtendweb
end users has nothing to do with this, it is more confusing than anything else

**Comment by AnoopAlias** [comment]
@yoorshop - As mentioned, XtendWeb's real goal is a Nginx web cluster and the title signify that.
Moreover, I believe the Nginx cluster will have widespread adoption in future. + the same cPanel UI is used in Cluster deployments. Making this a wontfix
