### ISSUE TITLE
Flexibility horizontal scaling

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#330]
Need feature in simple HA cluster to stop horizontal scaling , which means traffic is only directed to master, slave will be in action if naything goes wrong at master : network, nginx, mysql
(these 3 thinsg must be tested separately to see in HA is working properly)
- some websites can only work this way, as remote write are affected by a various security things inside CMS
- web host can save money on putting only small server on slave, instead of 2 medimum servers

**Comment by AnoopAlias** [comment]
This issue is no longer relevant as cluster now has 
1. Geo-Load balancing or optional simple RoundRobin LB
2. MySQL read scalability
