### ISSUE TITLE
DKIM records not working in geoDNS

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#341]
DKIM records not working in geoDNS

**Comment by AnoopAlias** [comment]
Waiting for upstream bug to be closed https://github.com/abh/geodns/issues/108

**Comment by yoorshop** [comment]
if you adopt : 
https://github.com/AnoopAlias/XtendWeb/issues/350

then this case is closed

**Comment by AnoopAlias** [comment]
Fixed in commit - https://github.com/AnoopAlias/XtendWeb/commit/96427e84ce48d15b34cdf0d48d355f7765a92d3e
