### ISSUE TITLE
Please add ngx_http_referrer module

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#344]
Please add ngx_http_referrer module to the installation:
http://nginx.org/en/docs/http/ngx_http_referer_module.html

**Comment by AnoopAlias** [comment]
@atxcowboy - This module is already enabled 

You can simply add /home/$CPANELUSER/public_html/nginx.conf

with config like

```
valid_referers none blocked server_names *.domain.com;
if ($invalid_referer) {
    return 403;

```

and in cPanel >> XtendWeb >>[ select domain] >> APPLICATION SETTINGS

Click on the RELOAD button for custom nginx.conf 

and the custom setting should work.

Please also upgrade to latest rpm as it provides logs for nginx config tests etc .I haven't send out the upgrade notifications yet as the documentation need to be updated

You can upgrade using instructions below

```
yum --enablerepo=ndeploy upgrade
/opt/nDeploy/scripts/attempt_autofix.sh
nginx -t  
#if all ok
systemctl restart nginx
```
Feel free to open a support ticket if you face any issues in activating the valid referrer settings.

**Comment by AnoopAlias** [comment]
closing this
