### ISSUE TITLE
Mail cluster

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#348]
I am looking for a way to have a high availability mail service beyond secondary MX life.
I had like to be able to have mail services available even when the master server is down

**Comment by AnoopAlias** [comment]
Users will be able to send mail from
1. php scripts (sendmail)
2. Authenticated Email ( SMTP Auth)

On all servers in cluster

2. User will be able to retrieve email only from master server with POP/IMAP as it is the only server that is storing email in in a mailDir on the filesystem. the slave servers act as backupMX and accept mail for /etc/localdomains and forward the same to master based on its availability
