### ISSUE TITLE
AutoSSL and SSL hooks instead of watcher triggers in cPanel v72

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#349]
As of cPanel v70 stable. the hooks are not active. Waiting for these hooks to be active in cPanel v72

**Comment by yoorshop** [comment]
No... UI end user + custom nginx.conf option are the needed things that akready exist.

I don't want users to have a view on ndeploy domain-ata file, neither the ful nginx content of config which is confidential at some point : know how

Moreover messing ndeploy backend, or general nginx conf is not acceptable

**Comment by vacancy12345** [comment]
Good news...

https://blog.cpanel.com/new-ssl-standard-hooks-for-cpanel-whm-integrators/
