### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by IkenHuub** [AnoopAlias/nDeploy#354]
Hi,

Why do I get this when trying to install?

[root@root ~]# yum -y --enablerepo=ndeploy install nginx-nDeploy nDeploy

failure: repodata/repomd.xml from ndeploy: [Errno 256] No more mirrors to try.
https://autom8n.com/CentOS/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
[root@root ~]#
​
Regards​

**Comment by AnoopAlias** [comment]
As mentioned in the support ticket you opened, access to the software repository needs a subscription

The product itself is opensource.

The project follows the RHEL subscription model
