### ISSUE TITLE
is there a way to add a version number every time there is an upgrade tp Xtendweb and show in whm ?

### ISSUE THREAD

**Issue by spirogg** [AnoopAlias/nDeploy#355]
is there a way to add a version number to Xtendweb, so every time there is an upgrade we see in whm XtendWeb version 4.5-19 etc.. and we know the upgrade worked ?

thanks

**Comment by AnoopAlias** [comment]
XtendWeb is distributed as an RPM package and the way to check version is

rpm -qa|grep nDeploy 

This will show the current version of all software including XtendWeb and Nginx
