### ISSUE TITLE
question - anyway to get sub domains to use different phpversion nginx and apache with Xtendweb ?

### ISSUE THREAD

**Issue by spirogg** [AnoopAlias/nDeploy#358]
just a question, is it possible to use Xtendweb to select a different php version on a subdomain ? 
example: sub.domain.tld will use nginx php7.0
sub1.domain.tld will use apache + reverse proxy with php7.2 
domain.tld will use nginx with php7.1

is this possible now just wondering

thanks

Spiro

**Comment by AnoopAlias** [comment]
Yes. You can configure the main domain, sub-domains and addon-domains individually from the cPanel XtendWeb UI
