### ISSUE TITLE
How to add directives from #35 to both PROXY & PHP Backend Configurations

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#36]
@AnoopAlias 

How can I add the directives I submitted in https://github.com/AnoopAlias/nDeploy/pull/35 so that they are applied to both PROXY & PHP based configurations? 

Thanks!

**Comment by AnoopAlias** [comment]
You can  add them to the template files in /opt/nDeploy/conf/xxxx.tmpl files

Proxy templates are in 1000 -1600 range
PHP in 5000 5600 range

If you are using custom templates it may be 9000-9999 range too 

Once you edit the template you can generate the config for all domains using

```

for CPANELUSER in $(cat /etc/domainusers|cut -d: -f1)
    do
        echo "ConfGen:: $CPANELUSER" && /opt/nDeploy/scripts/generate_config.py $CPANELUSER
    done
    service nginx restart

```
