### ISSUE TITLE
Feature request: version control

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#369]
Please consider adding version control for configuration files so that users can roll back to a certain previous configuration (preferably via a GUI).

**Comment by AnoopAlias** [comment]
@atxcowboy  -- you mean for the nginx template files like https://github.com/AnoopAlias/XtendWeb/blob/ndeploy4/conf/1000.j2 ?

**Comment by atxcowboy** [comment]
No, I had this in mind: /opt/nDeploy/domain-data

**Comment by AnoopAlias** [comment]
commit #49b5aad was wrongly tagged here. But the integrated borg backup would have the ability to rewind the domain-data to any retention point
