### ISSUE TITLE
Feature Request - Add Support/auto-creation for LetsEncrypt SSL certificates

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#37]

**Comment by AnoopAlias** [comment]
You can use Lets Encrypt in standalone mode

./letsencrypt-auto certonly --standalone -d piserve.com -d www.piserve.com

and generate the cert and key and use it in your cpanel ..just like any other cert.

I have done this for https://piserve.com/ and it works just fine .

Some tips:

python2.6 doesnt work . So it wont work fine in centos6 servers unless you use scl python27 . and enable python 27 using scl enable python27 bash

It should work just fine in centos7 as it already ships with python27.

**Comment by brianjking** [comment]
@AnoopAlias This works for both PROXY and PHP backends? Can you possibly update the Wiki with details as to how to implement this for both?

I'm on CentOS6 so having tips on how to deal with the Python issue would be appreciated.

**Comment by AnoopAlias** [comment]
This has nothing to do with nDeploy or nginx 

Please try 

./letsencrypt-auto certonly --standalone -d YOURDOMAIN_WHICH_NEEDS_SSL

this will create the key and crt . Copy paste in WHM like you do any other cert.

##

the letsencrypt cli is written in python and needs python27 to work correctly .How you get python27 is upto you . Having python27 installed via scl is one method which I mentioned.

This works for both PROXY and PHP backends -  is irrelevant - As I mentioned this has nothing to do with nginx or nDeploy . The letsencrypt people have complicated their website with some instructions that will setup the nginx/apache config I guess. But important thing is that they do support a standalone mode which lets us grab the cert via a text editor and add it from WHM/cpanel
