### ISSUE TITLE
Regenerate user nginx config following Transfer Tool / Migration

### ISSUE THREAD

**Issue by brixly** [AnoopAlias/nDeploy#371]
When an account (or multiple accounts / resellers) are migrated from one server to another, the configuration needs to be manually generated via the /opt/nDeploy/scripts/generate_config.py script.

Is it possible to do this automatically?

**Comment by AnoopAlias** [comment]
@brixly  - let me investigate this as this should be automatically handled by the create account hook

**Comment by vacancy12345** [comment]
Nice suggestion.

After sites migration, ssl certificates are not running, they start working after running autofix command, it is best to do this automatically.

**Comment by AnoopAlias** [comment]
@vacancy12345  -- Running autofix will regenerate all config.If you just need to do it for one single domain, you can do

`/opt/nDeploy/scripts/generate_config.py $cpaneluser`

I am checking why this is not triggered automatically
