### ISSUE TITLE
Before installing

### ISSUE THREAD

**Issue by onfire-d** [AnoopAlias/nDeploy#372]
Hi There,

I would like just to know af ew things before installing. Does the installation creates an "app" con cPanel (like LiteSpeed, CacheWall, Engintron.etc) where you can switch on or off the app (in this case nginx) and go back to cPanel default's configuration?

**Comment by AnoopAlias** [comment]
@desfire - yes the install create a WHM and cPanel plugin.

From the cPanel plugin a user will be able to switch his domain names individually between Native Nginx mode and a transparent PROXY mode(the default). Having the domain set to PROXY is in effect running the domain in cPanel default httpd environment with the connection just passing through Nginx
