### ISSUE TITLE
Make XTendweb cluster failover with cPanel paid license on slave

### ISSUE THREAD

**Issue by yoorshop** [AnoopAlias/nDeploy#377]
Title says it all, need full HA service with emails working 100%

**Comment by copernic2006** [comment]
+1 for emails,
it will be a great feature if it were to be added to Xtendweb.

**Comment by AnoopAlias** [comment]
I am closing this now as Apache service on slave DNS only is now supported

**Comment by yoorshop** [comment]
this feature has no relation with request which consist in using a real cpanel license on slave, which will allow use of same email services as on master, which would allow failover 100% working for emails...
