### ISSUE TITLE
RSS feeds in WordPress served as "text/html"

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#381]
RSS feeds located in /feed/ in WordPress are erroneously served as "text/html".
As a result of this, they do not completely validate, the format is messed up in chrome. and firefox wants to download a file.
RSS feeds should be served as application/rss+xml or at least the more general application/xml.

I tried to a location and add_header application/rss+xml, but nginx still serves Content-Type: text/html. 
I also tried to add a default_type without success.

**Comment by AnoopAlias** [comment]
@atxcowboy -- please would you open a ticket at ops@gnusys.net with the server IP and domain for which you face the problem.

Instructions to add my SSH keys -- https://autom8n.com/howtos/grant_access_to_autom8n_sysadmin.html

**Comment by AnoopAlias** [comment]
closed via support ticket #5954
