### ISSUE TITLE
Enable DDOS protection from WHM clusterwide

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#390]
Automatically deploy DDoS settings in WHM cluster-wide

**Comment by spirogg** [comment]
Will this be avail for all xtendweb even single server install ? Can you make avail from whm you can activate ddos protection for whole server all domains using shared IP. ?

**Comment by AnoopAlias** [comment]
@spirogg -- yes its available in standalone and the protection is activated server wide. You can activate dos protection on a per domain basis from the respective cPanel plugin UI
