### ISSUE TITLE
setup_borg_backup.cgi bug

### ISSUE THREAD

**Issue by xlightwaverx** [AnoopAlias/nDeploy#422]
```
        system_files = yaml_parsed_backupyaml.get('system_files')
        mysql_backup = yaml_parsed_backupyaml.get('mysql_backup')
```

mysql_backup pulls None from yaml parsing which causes Forbidden when attempting to save setting as save_backup_settings.cgi requires form data to run the function.

`if form.getvalue('system_files') and form.getvalue('mysql_backup'):`

Need to check for None and assign to disabled if yaml pull contains no data prior to above if statement.

**Comment by AnoopAlias** [comment]
The second commit #d89a41d was the actual fix . Issue happened because of html error due to a misplaced closing double quote :)
