### ISSUE TITLE
Please consider support for Webmin / Virtualmin

### ISSUE THREAD

**Issue by atxcowboy** [AnoopAlias/nDeploy#431]
In light of cPanel's new rip off policy, please add support for Webmin / VirtualMin.

**Comment by xlightwaverx** [comment]
Simply charge your clients more :)

**Comment by atxcowboy** [comment]
I talked to many customers and the feedback is mixed. Some are willing to pay more and particularly due to the lack of worthwhile immediate alternatives, they are willing to swallow the bitter pill. Some are going to consolidate services to adjust costs. For a lot of customers however it means that they need to look into alternatives, even if they are not as good as cPanel.
Their new pricing model has definitely opened up a market chance and who knows, maybe something great will arise in a few months.
Pretty much all customers I talked to feel alienated by the new short hand notices during summer time and they do not expect much innovation from cPanel in the future due to the new ownership. After all, innovation is one of the reasons why all of use are using XtendWeb, isn't it?

**Comment by xlightwaverx** [comment]
I think it would be best to pool our efforts into creating our own panel, something that can stand alone and does not require another company's software as a base.  Then the only one changing prices, would be us.

**Comment by AnoopAlias** [comment]
Weighing all options for other platforms. I am also considering an independent control panel that focuses on High Availability and Scalability. Just waiting to see how things turn out by September when the actual price hikes are in effect

**Comment by atxcowboy** [comment]
The independent control panel would probably be favorable for us.
We're also going to evaluate ISPConfig for some customers.
