### ISSUE TITLE
Moving from old nDeploy instance to YUM RPM based

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#5]
Hello,

When you installed nDeploy on my server the YUM repo wasn't available. Can you please advise on what I need to do to to now use the YUM based install method?

Thanks,
BK

**Comment by AnoopAlias** [comment]
Hello Brian,

Please update the ticket you have at support@sysally.net with the server login and I will do the changeover . Ideally if you install the http://rpm.piserve.com/nDeploy-release-centos-1.0-el6.noarch.rpm and follow https://github.com/AnoopAlias/nDeploy/wiki/Installation-Instructions .nDeploy and nginx-nDeploy would get updated automatically

Note that we are no longer maintaining the i386 version of the nginx package as most systems are x86_64 and I need to maintain a server with i386 arch to compile it . Hopefully you have x86_64 .But if not let me know and I can get some workaround :)

**Comment by brianjking** [comment]
I've changed how my server is connected to over SSH and would prefer not to send SSH keys over email. Can we connect another more secure way?

@AnoopAlias 

Thanks!

BTW - I'm on an 64bit AMD setup so that's fine.

**Comment by AnoopAlias** [comment]
Hi Brian,

If you have a lastpass account you can share the pass with me securely via lastpass (https://helpdesk.lastpass.com/sharing/ )

My lastpass email is anoop.alias@piserve.com

Alternately you can simply add my public key to the servers authorized_host file and grant me access:

###

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/FXDQWjr4tq/1ppv8yQM/krFnrb7Qn5HLK9IvWlJ+mW7rsBIkJwxCCB75CYVjEVPi973MkZXFrwFG9JTPXFMR0ZuLe8R3GAAL2cTXPxwKSC+77WpQJrQT6eOV7bgRNsPHvWcbmJass5ttlErRgT0o++MYOSR4SmzlV3mn0w+/oGfIsOWBuBXIJ1MHh1M11ZjEoHda1A0tjXMgnLMUMaNIRmvBtEyZgLSrwLce92Bcm0gfh5UXAl+JleBbPXGK9Iwna6d43QwiwMj/iBEFPOL8I8FgUt5m9QDPLLNqRmjWMq/qpjVZgNb4bApj7rmQmi5fRJNOnc/WDe77OhCF4FBn z@z-ThinkPad


###

Thanks

**Comment by brianjking** [comment]
Hello,

I've added your ssh key. Can we possibly work on this tonight Eastern Standard Time? If so, please contact me prior to connecting.

Thanks!

**Comment by AnoopAlias** [comment]
Hi,

Can you send the server name or main ip with ssh port if any to support@sysally.net.

Thanks

**Comment by brianjking** [comment]
Done. Please ping me on skype or email @brianjking prior to starting work.
