### ISSUE TITLE
Users with dedicated IP

### ISSUE THREAD

**Issue by bashcode** [AnoopAlias/nDeploy#55]
Hello,

In latest nDeploy version, users with dedicated ips is not working.

Thanks

**Comment by AnoopAlias** [comment]
Can you run /opt/nDeploy/scripts/generate_config.py USER 

and let me know if it shows any error.

**Comment by bashcode** [comment]
Fixed when run /opt/nDeploy/scripts/generate_config.py USER, and reload nginx.

Thanks

**Comment by AnoopAlias** [comment]
This is the same script that the watcher calls when you change IP etc. Nit sure what went wrong there.

I will close this for now. Feel free to reopen if you still face an issue
