### ISSUE TITLE
PHP Backend Widget doesn't support Multi-Master PHP

### ISSUE THREAD

**Issue by xlightwaverx** [AnoopAlias/nDeploy#573]
The PHP Backend Widget is only coded to check Single Master PHP.  It reports as "Issues Detected" as its not picking up the processes in ps.

**Comment by AnoopAlias** [comment]
This may not be possible as we run a master process per user. A fix would be to check if multi-master is enabled and then show a friendly message instead of the "Issue detected"

**Comment by xlightwaverx** [comment]
Can do.
