### ISSUE TITLE
cPanel 11.54 edit custom config does not output the nginx conf correctly in textarea

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#58]
Looks like the conf file is mangling with the page html as the conf is not properly html escaped.

Escaping html seems to complicate things as well. 

Looks like we may need to provide a hint and save the current config in user home so users can download ,edit and update with the custom config update script.

It would be a step backward on the usability side..but looks like that is the only option  available.

**Comment by brianjking** [comment]
@AnoopAlias If I upgrade cPanel to 11.54 what are the implications of this issue?

**Comment by AnoopAlias** [comment]
@brianjking  - It may cause issues in the "MANUAL" config edit mode in the cPanel plugin UI. 

If you dont have any custom config and dont want to edit the conf via cPanel plugin UI its fine to upgrade.

**Comment by brianjking** [comment]
@AnoopAlias I do have some custom "MANUAL" config's.

If I edit these via SSH am I okay to upgrade?

**Comment by AnoopAlias** [comment]
@brianjking - yes. I will fix this in a day or two. Just couldn't squeeze out time for this and thought this wasnt a critical issue.
