### ISSUE TITLE
Wiki broken ? :(

### ISSUE THREAD

**Issue by PunKeel** [AnoopAlias/nDeploy#61]
Hello,

The wiki is broken :-( https://support.sysally.net/projects/ndeploy/wiki

Are there any reasons on why you're not using the Wiki hosted by Github ? :-)

Regards !

EDIT: looks like it was the case before https://github.com/AnoopAlias/nDeploy/blob/0ec6c939ca459bce326c92756d00a8dfd4998431/rpm_buildtree/nDeploy-pkg/opt/nDeploy/README.md

**Comment by AnoopAlias** [comment]
Hi,

Apologies..the redmine wiki should be back online now. 

I had a disagreement with the font on GitHub Wiki.  It looked too much cluttered . :)
