### ISSUE TITLE
Feature Request - Remove Cluster DNS in WHM

### ISSUE THREAD

**Issue by brixly** [AnoopAlias/nDeploy#626]
Can you please add an option in either whm or cPanel which allows us to run the following script...

To Clean up DNS zone of additional A records and MX

touch /opt/nDeploy/conf/DECLUSTER_DNSZONE /opt/nDeploy/scripts/cluster_dns_ensure_user.py $CPANELUSER rm -f /opt/nDeploy/conf/DECLUSTER_DNSZONE

Is it possible this is added as an option in WHM, or something similar so we can decluster from the interface?

**Comment by xlightwaverx** [comment]
+1 from me :)
