### ISSUE TITLE
Add Template for Silverstripe v4

### ISSUE THREAD

**Issue by purplespider** [AnoopAlias/nDeploy#629]
The current "[SilverStripe](https://github.com/AnoopAlias/AUTOM8N/blob/efcf58146d8de7c93b04700071d018dd8ccfc005/conf/5013.j2)" template seems to only work for older SilverStripe version 3 sites.

Would it be possible to add a template for the newer SilverStripe v4?

The main difference is that the public root is no longer `public_html` but is now `public_html/public`.

There appears to be an official recipe for SilverStripe 4 here: https://www.nginx.com/resources/wiki/start/topics/recipes/silverstripe/ 

Thanks!

**Comment by AnoopAlias** [comment]
The template is added and will be available in the next RPM upgrade

**Comment by AnoopAlias** [comment]
Just FYI .. the new RPM is available in the repo with this template added

**Comment by purplespider** [comment]
Thanks for adding this Anoop, but I'm struggling to get it to work. It may just be that the public root of a Silverstripe 4 site should be: `{{ DOCUMENTROOT }}/public` rather than just `{{ DOCUMENTROOT }}` (presume DOCUMENTROOT is `public_html`?)

I'm happy to refine and test this for you, by using a custom `nginx.conf` in the site root, but I keep getting ` Invalid/Require Reload`, even when using the basic template from here: https://autom8n.com/docs/Application_template.html

So if you can help with a valid starting point, I'll do the rest!

**Comment by xlightwaverx** [comment]
Hi James,

You can make this change in /opt/nDeploy/conf/5050.j2 and reapply the
template after your changes. We can update the RPM after you get a working
version running.

**Comment by AnoopAlias** [comment]
@purplespider yes directly edit the template file and run

/opt/nDeploy/scripts/generate_config.py USER
nginx -s reload

or you can simply test this by directly editing the generated config at

/etc/nginx/sites-enabled/domain.com.include
nginx -s reload

If it's working, You can tell here or better send in a pull request for the change :)

**Comment by purplespider** [comment]
Thanks both. Unfortunately, I'm an end-user of a host using Autom8n, so I don't have that level of access. 

Is there no way I can use the `public_html/nginx.conf` feature to help here?

**Comment by AnoopAlias** [comment]
@purplespider  Unfortunately no .. because the root directive is already defined in the template 

https://github.com/AnoopAlias/AUTOM8N/blob/ndeploy4/conf/5050.j2#L3

and nginx.conf would not allow a duplicate 

But I am sure your host will understand this and ready to make the change if you open a support ticket with them. If they don't let me know and I will create a test environment to test this out with a SilverStripe v4 install. 

Perhaps you can get the issues to link shared with the host, so they understand what's going on
