### ISSUE TITLE
Error rebuilding config with IPv6 address

### ISSUE THREAD

**Issue by dotsam** [AnoopAlias/nDeploy#67]
When modifying an account with an IPv6 address assigned, the following error is generated from generate_config.py

```
Domain::Data::Modify thenumber
Traceback (most recent call last):
  File "/opt/nDeploy/scripts/generate_config.py", line 568, in <module>
    nginx_confgen(cpaneluser, main_domain)  # Generate conf for main domain
  File "/opt/nDeploy/scripts/generate_config.py", line 437, in nginx_confgen
    ipv6_addr = str(yaml_parsed_cpaneldomain.get('ipv6').keys()[0])
AttributeError: 'str' object has no attribute 'keys'
```

There's only a single `ipv6` key in the userdata yaml for this account, and it looks like you're not handling that case correctly?

**Comment by AnoopAlias** [comment]
@dotsam - I will check this out

**Comment by AnoopAlias** [comment]
@dotsam - I  checked this on a test server and it was working fine . Yes there is only one ipv6 key .

But yaml_parsed_cpaneldomain.get('ipv6') is a list in python for yaml like

`ipv6:
  2400:6180:0000:00d0:0000:0000:0159:6000:
    dedicated: 1
`

The first key being the ipv6 address itself.

Can you paste the ipv6 segment in

`/var/cpanel/userdata/thenumber/<DOMAIN>`

Note that you need to setup ipv6 from WHM 

Home »IP Functions »IPv6 Ranges

add the range

and then

Home »IP Functions »Assign IPv6 Address

to assign a single address to the domain

**Comment by dotsam** [comment]
It looks like IPv6 somehow became disabled for this account, but the IPv6 key was maintained, but without the "dedicated" sub-key. Assigned the IPv6 address to this account again and everything is working fine.

Probably a very-strange edge-case, but there it is, if you want to handle it.

**Comment by AnoopAlias** [comment]
Whatever went wrong made yaml_parsed_cpaneldomain.get('ipv6') into a string ;while it should actually be a list .So the .keys() became invalid on the string data type

But as I mentioned if the ipv6 is set up correctly in WHM everything works!

**Comment by dotsam** [comment]
I've been seeing this issue intermittently again when the config_generation_queue_runner.sh cron job runs. The errors are mostly overnight, so no changes are being made to accounts at that time. Sounds like there's a cPanel bug where things become un-set in the userdata during certain maintenance tasks perhaps? I think it might be wise to add some error-handling to the ipv6 part of the config generation script.

**Comment by AnoopAlias** [comment]
@dotsam - can you confirm the error is 

```
ipv6_addr = str(yaml_parsed_cpaneldomain.get('ipv6').keys()[0])
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by dotsam** [comment]
Yes, the full error is
```
Traceback (most recent call last):
 File "/opt/nDeploy/scripts/generate_config.py", line 672, in <module>
   nginx_confgen(cpaneluser, main_domain)  # Generate conf for main domain
 File "/opt/nDeploy/scripts/generate_config.py", line 489, in nginx_confgen
   ipv6_addr = str(yaml_parsed_cpaneldomain.get('ipv6').keys()[0])
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by AnoopAlias** [comment]
@dotsam  - Can you try

`wget -O /opt/nDeploy/scripts/generate_config.py /https://raw.githubusercontent.com/AnoopAlias/nDeploy/master/scripts/generate_config.py`

If alls ok.I will get it included in the rpm

**Comment by dotsam** [comment]
Didn't see any errors overnight, everything seems to be working correctly, with IPv6 addresses being parsed correctly out of user data.
