### ISSUE TITLE
Support the installation of LetsEncrypt SSL certs from the nDeploy plugin 

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#69]

**Comment by brianjking** [comment]
@AnoopAlias Can you elaborate on what you're going to be adding here and when you expect it may be implemented?

Thanks!

**Comment by AnoopAlias** [comment]
@brianjking A LetsEncrypt plugin (hopefully) to the nDeploy webstack. It will ideally be installing the cert using cPanel API. No ETA at the moment as I am yet to check out whats involved . But from the looks of it.it should be fairly simple

**Comment by brianjking** [comment]
@AnoopAlias Ooh, nice. Can you please advise as to the setup of this? I see the option in the newest update, however, I haven't installed LetsEncrypt on my cPanel server yet. I've just been using https://www.sslforfree.com/

**Comment by AnoopAlias** [comment]
@brianjking  -  https://support.sysally.net/projects/ndeploy/wiki/LetsEncrypt_setup

In short all you need to do is install LetsEncrypt (the latest) anywhere and create /opt/nDeploy/conf/letsencrypt.yaml with the path to letsencrypt binary . nDeploy will take care of the rest . 

FYI ..it use the webroot plugin . So it creates a folder .well-known/acme/xxxxx unique file in your public_html and calls it via http for verification. The domain name must therefore point to the server and there should not be anything blocking the access to .well-known folder.

**Comment by brianjking** [comment]
@AnoopAlias 3 questions to verify:

1. I can selectively enable SSL only on the domains in which I choose, leaving the others as Non-SSL, correct?

2. This works for Proxy as well as PHP Backend modes?

3. It auto-handles the renewals?

**Comment by AnoopAlias** [comment]
@brianjking 

1. Yes .. this presents a drop down of domains and you have to manually flip it to enable to enable LetsEncrypt for a domain

2. Yes mode is irrelevant

3. See the doc. You need to add a cron job for root which will auto renew the certs (all certs!) which expire in the next 30 days.
