### ISSUE TITLE
Default Server Changes

### ISSUE THREAD

**Issue by dotsam** [AnoopAlias/nDeploy#71]
I'd like to see the default_server.conf changed to also listen on the host's shared IPv6 address if applicable, and also have a default https server (also listening on IPv6 and IPv4 shared address) in order to ensure that all web requests coming in go somewhere, even if that's just to the WHM "Default Web Site" page.

**Comment by AnoopAlias** [comment]
@dotsam   -Ah yes the ipv6 use case never came up mainly because very few people actually cared about it I guess. I will get this fixed shortly.
