### ISSUE TITLE
LetsEncrypt Installed via Wiki, not working

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#72]
Hi @AnoopAlias 

I have installed LetsEncrypt and created the yaml file as per the wiki instructions below. I have enabled this for a PROXY as well as PHP backend setup, neither appear to be working.

I'm not seeing any .well-known folders being created or anything either in the domains which is what I'd expect.

Please advise...

https://support.sysally.net/projects/ndeploy/wiki/LetsEncrypt_setup

**Comment by AnoopAlias** [comment]
@brianjking  - After you enable letsencrypt for a domain. run the following from commandline

`/opt/nDeploy/scripts/generate_config.py CPANELUSER`

Paste any relevant errors you see there.

**Comment by AnoopAlias** [comment]
Hi Brian,

Just wanted to check up with you and see if this is sorted. We have a new release that fixed a bug  in letsencrypt setup
Let me know if I can consider this resolved.

**Comment by AnoopAlias** [comment]
@brianjking - I will close this bug report assuming you were able to get it working /figure it out.

Feel free to reopen this anytime .
