### ISSUE TITLE
Avast malware warning when attempting to view nDeploy Website on Windows 10?

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#77]
![avast-ndeploy](https://cloud.githubusercontent.com/assets/6786817/15057076/acf0df9e-12da-11e6-947f-6c1ee87c665f.png)

So, when attempting to visit https://support.sysally.net/projects/ndeploy/wiki on Windows 10 I'm suddenly getting this warning from Avast.

I can still pull up the page via Mac & Linux without an issue, however, these obviously are not running Avast Antivirus.

Any ideas?

**Comment by AnoopAlias** [comment]
Hi Brian,

Its a redmine install . 

https://sitecheck.sucuri.net/results/support.sysally.net/projects/ndeploy/wiki - looks fine

Perhaps avast is trying to sell you their product :)

**Comment by AnoopAlias** [comment]
@brianjking - Closing .
