### ISSUE TITLE
Including CORS config in a PHP Backend Configuration

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#79]
````
#
# Wide-open CORS config for nginx
#
location / {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
     }
}
````

**Comment by brianjking** [comment]
@AnoopAlias I wanted to add the above CORS configuration to my domain which uses a PHP Backend.

* Which file should I add this to?
* Domain is using SSL so should I add this to the domain.com or domain.com (SSL) configuration?

I tried creating a nginx-cors.conf file and including this, however, I'm getting a duplicate location error.

**Comment by AnoopAlias** [comment]
@brianjking  - You can do the MANUAL edit mode in cPanel and include all that config additionally with what is already there in the automatic configuration.

Note that the location / {} will be already there in the auto configuration .So you just need to include 
` if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
     }`

inside that location

**Comment by AnoopAlias** [comment]
The config lost the line breaks ; but I guess you understood what I meant .Closing this now

**Comment by brianjking** [comment]
@AnoopAlias Do I add this to the SSL or non-ssl cPanel config?

**Comment by AnoopAlias** [comment]
@brianjking - both ssl and non-ssl . If you are redirecting non-ssl to ssl, then you need to do this only on the SSL one otherwise both need to be edited.

**Comment by brianjking** [comment]
@AnoopAlias This is for the domain we talked about on Skype the other night, so it's SSL with a PHP Backend.

When I added this config to the SSL domain config and curl -I https://domain.com I wasn't getting any headers for the CORS configuration.

I could certainly use some help 😦

**Comment by brianjking** [comment]
Just as a note CORS works fine when I switch the domain to proxy mode.

**Comment by brianjking** [comment]
@AnoopAlias Any idea about this? https://github.com/AnoopAlias/nDeploy/issues/79#issuecomment-219202878

**Comment by AnoopAlias** [comment]
@brianjking  - Please confirm the edits you made has indeed been set in the nginx configs in
/etc/nginx/sites-enabled/domain_SSL.include 

if yes then it should work.
