### ISSUE TITLE
Receive an error message when you try to install

### ISSUE THREAD

**Issue by Nirjonadda** [AnoopAlias/nDeploy#8]
Hello,

I am getting error message when you try to install, If run : /usr/nginx/scripts/nginx-passenger-setup.sh, Please can you let me know, How to fixing this error ?

root@rg [~]# /usr/nginx/scripts/nginx-passenger-setup.sh
 Setting up Phusion Passenger
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: keyserver timed out
gpg: keyserver receive failed: Keyserver error
Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
gpg: Signature made Mon 30 Mar 2015 05:52:13 PM EDT using RSA key ID BF04FF17
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.11.tgz' - 'https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc'!
try downloading the signatures:

    sudo gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

/usr/nginx/scripts/nginx-passenger-setup.sh: line 5: rvm: command not found
/usr/nginx/scripts/nginx-passenger-setup.sh: line 8: /usr/local/rvm/rubies/ruby-2.2.2/bin/gem: No such file or directory
ln: target `/usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.11/' is not a directory: No such file or directory
Stopping nginx:                                            [FAILED]
Starting nginx: nginx: [emerg] bind() to 194.145.208.207:80 failed (98: Address already in use)
nginx: [emerg] bind() to 194.145.208.207:80 failed (98: Address already in use)
nginx: [emerg] bind() to 194.145.208.207:80 failed (98: Address already in use)
nginx: [emerg] bind() to 194.145.208.207:80 failed (98: Address already in use)
nginx: [emerg] bind() to 194.145.208.207:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()                 [FAILED]

root@rg [~]# /opt/nDeploy/scripts/cpanel-nDeploy-setup.sh enable
httpd restarted successfully.
Stopping nginx:                                            [FAILED]
Starting nginx: nginx: [alert] Unable to start Phusion Passenger: Support binary PassengerAgent not found (tried: /usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.11/buildout/support-binaries/PassengerAgent and /root/.passenger/support-binaries/5.0.11/PassengerAgent). This probably means that your Phusion Passenger installation is broken or incomplete, or that your 'passenger_root' setting contains the wrong value. Please reinstall Phusion Passenger or adjust the setting (see: https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerRoot). (-1: Unknown error)
                                                           [  OK  ]
Shutting down Filesystem event daemon (incrond):           [FAILED]
Starting Filesystem event daemon (incrond):                [  OK  ]
Stopping nginx:                                            [  OK  ]
Starting nginx: nginx: [alert] Unable to start Phusion Passenger: Support binary PassengerAgent not found (tried: /usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.11/buildout/support-binaries/PassengerAgent and /root/.passenger/support-binaries/5.0.11/PassengerAgent). This probably means that your Phusion Passenger installation is broken or incomplete, or that your 'passenger_root' setting contains the wrong value. Please reinstall Phusion Passenger or adjust the setting (see: https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerRoot). (-1: Unknown error)

**Comment by AnoopAlias** [comment]
*gpg: keyserver timed out*

The above is your core issue. See if you have an issue with your firewall or something related to network connectivity . Additionally if you are just hosting PHP websites you dont need passenger and can skip running the command nginx-passenger-setup.sh
