### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by justvanbloom** [AnoopAlias/nDeploy#81]
Traceback (most recent call last):
 File "/opt/nDeploy/scripts/generate_config.py", line 665, in <module>
   nginx_confgen(cpaneluser, main_domain)  # Generate conf for main domain
 File "/opt/nDeploy/scripts/generate_config.py", line 595, in nginx_confgen
   nginx_confgen_profilegen(user_name, domain_sname, cpanel_ipv4, document_root, 0, domain_home, *domain_aname_list)
 File "/opt/nDeploy/scripts/generate_config.py", line 240, in nginx_confgen_profilegen
   profile_category = yaml_parsed_profileyaml.get('backend_category')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by AnoopAlias** [comment]
One of the domain-data file in /opt/nDeploy is non existent or incomplete. User exceeding quota is a known cause of incomplete domain data file. See if you can find a file with 0 size in domain-data folder and remove it. Fix the quota and running attempt _autofix.sh should recreate it

**Comment by AnoopAlias** [comment]
@justvanbloom - Hopefully you were able to resolve this. I am closing this now
