### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by r3zo** [AnoopAlias/nDeploy#82]
Hi, im trying to update the ndeploy but it says error downloading packages:

Total size: 44 M
Total download size: 44 M
Is this ok [y/N]: y
Downloading Packages:
http://rpm.piserve.com/CentOS/6/x86_64/nginx-nDeploy-1.10.0-7.el6.x86_64.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 416 Requested Range Not Satisfiable"
Trying other mirror.

Error Downloading Packages:
  nginx-nDeploy-1.10.0-7.el6.x86_64: failure: nginx-nDeploy-1.10.0-7.el6.x86_64.rpm from ndeploy: [Errno 256] No more mirrors to try.

**Comment by AnoopAlias** [comment]
Error looks like a network issue on your end.

Please see: https://www.centos.org/forums/viewtopic.php?t=4766

**Comment by r3zo** [comment]
Hi Anoop, i have reported this issue to support and they replied with this:

This is not a problem with the connectivity of the VPS, as it was able to install the "htop" package without an issue:

Dependencies Resolved

============================================================================================================================================================================================================================================
Package Arch Version Repository Size
============================================================================================================================================================================================================================================
Installing:
htop x86_64 1.0.3-1.el6 epel 83 k

Transaction Summary
============================================================================================================================================================================================================================================
Install 1 Package(s)

Total download size: 83 k
Installed size: 178 k
Is this ok [y/N]: y
Downloading Packages:
htop-1.0.3-1.el6.x86_64.rpm | 83 kB 00:00 
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Installing : htop-1.0.3-1.el6.x86_64 1/1 
Verifying : htop-1.0.3-1.el6.x86_64 1/1 

Installed:
htop.x86_64 0:1.0.3-1.el6 Complete!



If you take a closer look at the error with ndeploy it states"Package does not match intended download." which is definitely not a network issue.

**Comment by r3zo** [comment]
Hi, i don't know what happened but the update is working without any issue now.

It seems it started working again.

Thank you again
