### ISSUE TITLE
implement security for Zend OpCache is php-fpm pool file 

### ISSUE THREAD

**Issue by AnoopAlias** [AnoopAlias/nDeploy#83]
https://github.com/zendtech/ZendOptimizerPlus/issues/89

php_admin_value[opcache.restrict_api] = /home/$pool/

would be good unless the user use something like /home2

**Comment by mdpuma** [comment]
ok, but this is whitelist for opcache api commands

This will not separate cached files from distinct users.

User1 still can read file which is cached by User2.

**Comment by AnoopAlias** [comment]
ok not sure how this works .But I think this is the best we got for securing a shared opcache right now

**Comment by mdpuma** [comment]
oh, you not restrict anything with this directive!

all users will have access to opcache_status as example, which will show cached files list from ALL accounts

**Comment by AnoopAlias** [comment]
the best route for strong security on the shared environment is having a php-fpm master process per user . But it would be an overkill considering many cPanel servers have 500+ user accounts.

and managing the master process etc will be cumbersome.

**Comment by mdpuma** [comment]
i agree, but anyway, you not make more securely php for clients with this directive

if you want to secure this somehow, see at opcache.blacklist_filename.

Doesn't cache wp-config.php, config.php or something similar ;)
