### ISSUE TITLE
Uninstall not successful

### ISSUE THREAD

**Issue by Nirjonadda** [AnoopAlias/nDeploy#9]
l am uninstalled nDeploy but under cPanel still showing this option. please let me know, how to delete nDeploy files completely?

http://prntscr.com/7pyyqb

**Comment by AnoopAlias** [comment]
Can you run an upcp . I will incorporate the plugin uninstall which was recently implemented by cPanel in next release . Just note that the plugin files are uninstalled and its cPanel interface icon cache showing the cached icons

**Comment by AnoopAlias** [comment]
This issue is fixed by providing the plugin_uninstall in the rpm pre_uninstall script.

Update rpm to nDeploy-1.0-26.el6.noarch.rpm
