### ISSUE TITLE
unison not working on latest nDeploy

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#94]
3 nodes Whole Stack Cluster
CPanel 11.58/EA4
MariaDB 10.1 galera cluster
installed everything else as documented here 
http://ndeploy.readthedocs.io/en/latest/nDeploy_cluster_setup.html

Next I imported my accounts from previous CPanel 11.58 to new Master CPanel 11.58
Home>Transfers>Transfer Tool

Then upgraded according to
http://ndeploy.readthedocs.io/en/latest/Upgrade_cluster.html

Waited 24H and then did a check on slaves CPanel DNSOnly
ls -alh /home/
df -h

Found out the unison /home replication didn't occurred!

I have tried to run the script manually but get this ERROR
/opt/nDeploy/scripts/cluster_home_ensure_all.py

ERROR! Missing target hosts
^CTraceback (most recent call last):
  File "/opt/nDeploy/scripts/cluster_home_ensure_all.py", line 12, in <module>
    subprocess.call('/usr/bin/ansible -i /opt/nDeploy/conf/nDeploy-cluster/hosts -m user -a "name='+cpaneluser+' home='+cpaneluserhome+'"', shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1376, in wait
Traceback (most recent call last):
  File "/usr/bin/ansible", line 21, in <module>
    from __future__ import (absolute_import, division, print_function)
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
KeyboardInterrupt  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call

PLEASE HELP!
Everything else work beautifully!

**Comment by AnoopAlias** [comment]
ERROR! Missing target hosts means your ansible hosts file may not be set correctly .

check /opt/nDeploy/conf/nDeploy-cluster/hosts file

Also if you are migrating accounts to a fresh server ; you need not call the script /opt/nDeploy/scripts/cluster_home_ensure_all.py manually. the account creation in cPanel would trigger that script and add the user and create the home directory in all the slaves in the cluster.

You can check if unison is running by

ps aux|grep unison

In previous versions of nDeploy unison was triggered by lsyncd on filesystem events . This was making the stack more complex. So now lsyncd is out of the picture and unison is started by a systemd/init startup file (ndeploy_unison) and then runs forever . 

I have personally seen unison terminating without spitting an informative error to trace ;so we have been monitoring unison in the servers we manage in ps output using nagios. Its not a frequent occurrence ..but happens like once in a blue moon.

**Comment by sergeng** [comment]
[root@web-01 modules]# cat  /opt/nDeploy/conf/nDeploy-cluster/hosts
[ndeployslaves]
web-02.domain.name ansible_port=22
web-03.domain.name ansible_port=22

[ndeploymaster]
web-01.domain.name ansible_port=22 ansible_connection=local

[root@web-01 modules]# ps aux|grep unison
root      7455  0.0  0.0 112648   972 pts/0    S+   14:44   0:00 grep --color=auto unison

[root@web-01 modules]# systemctl status ndeploy_unison.service
â— ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; enabled; vendor preset: disabled)
   Active: active (exited) since Sat 2016-08-27 18:43:05 JST; 20h ago

Aug 27 18:43:05 web-01.domain.name systemd[1]: Starting nDeploy Unison...
Aug 27 18:43:05 web-01.domain.name systemd[1]: Started nDeploy Unison.

Apparently the account creation in cPanel may have have trigger the /opt/nDeploy/scripts/cluster_home_ensure_all.py script but as you can see
the accounts have not been synchronized on any of the slaves;
[root@web-01 modules]# du -sh /home/
98G     /home/
[root@web-02 modules]# du -sh /home/
1.1M    /home/
[root@web-03 ~]# du -sh /home/
1.1M    /home/

So which log to pinpoint the error?
and
How to replay the process?
or
How to fix it manually without the error previously mentioned?

Thank you

**Comment by AnoopAlias** [comment]
you don't have unison running .

do

systemctl start ndeploy_unison

Also ensure web-02.domain.name etc resolve correctly 

if useraccounts are already created ..just starting unison would sync the files.


Unison also logs to 

logfile = /var/log/unison-<slave-hostname>.log and you can see if its syncing content in the log

**Comment by sergeng** [comment]
Was getting error in the log;
`[root@web-01 tasks]# tail -f /var/log/unison-web-02.domain.name.log 
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server
Fatal error: Lost connection with the server`

This post gave me the hint;
https://ubuntuforums.org/showthread.php?t=1733811&p=11596375#post11596375

So I checked the slave;
`[root@web-02 GeoIP]# systemctl status ndeploy_unison
â— ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@web-02 GeoIP]# systemctl enable ndeploy_unison
Created symlink from /etc/systemd/system/multi-user.target.wants/ndeploy_unison.service to /usr/lib/systemd/system/ndeploy_unison.service.
[root@web-02 GeoIP]# systemctl start ndeploy_unison 
Job for ndeploy_unison.service failed because the control process exited with error code. See "systemctl status ndeploy_unison.service" and "journalctl -xe" for details.
[root@web-02 GeoIP]# systemctl status ndeploy_unison
â— ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2016-08-28 17:11:48 JST; 8s ago
  Process: 7279 ExecStart=/opt/nDeploy/scripts/init_unison.py start (code=exited, status=203/EXEC)

Aug 28 17:11:48 web-02.globaal.net systemd[1]: Starting nDeploy Unison...
Aug 28 17:11:48 web-02.globaal.net systemd[1]: ndeploy_unison.service: control process exited, code=exited status=203
Aug 28 17:11:48 web-02.globaal.net systemd[1]: Failed to start nDeploy Unison.
Aug 28 17:11:48 web-02.globaal.net systemd[1]: Unit ndeploy_unison.service entered failed state.
Aug 28 17:11:48 web-02.globaal.net systemd[1]: ndeploy_unison.service failed.`

So I checked the startup script;
`[root@web-02 GeoIP]# cat /usr/lib/systemd/system/ndeploy_unison.service 
[Unit]
Description=nDeploy Unison
After=network.target remote-fs.target nss-lookup.target sshd.service

[Service]
Type=forking
ExecStart=/opt/nDeploy/scripts/init_unison.py start
ExecStop=/opt/nDeploy/scripts/init_unison.py stop
User=root
Group=root
TimeoutSec=300
StandardOutput=tty
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
[root@web-02 GeoIP]# cat /opt/nDeploy/scripts/init_unison.py           
cat: /opt/nDeploy/scripts/init_unison.py: No such file or directory
[root@web-02 GeoIP]# `

**There is no startup script on the slave!**
Please advise.

**Comment by AnoopAlias** [comment]
unison dont need the startup script on slave but the unison binary itself is needed on the slave which is installed by the cluster setup.

https://github.com/AnoopAlias/nDeploy/blob/master/conf/nDeploy-cluster/roles/install_slave/tasks/main.yml

```
- name: Install nDeploy cluster slave rpm packages
  yum: name={{ item }} enablerepo=ndeploy,epel state=present
  with_items:
   - csync2-nDeploy
   - unison-nDeploy
   - nginx-nDeploy
   - nDeploy-cluster-slave
```

The above packages are all installed on the slave .If not there is a problem with the cluster setup!

**Comment by AnoopAlias** [comment]
Fatal error: Lost connection with the server Fatal error: Lost connection with the server Fatal error

Tells me the error lies somewhere in your hostname resolution . That should be where you need to check.

/opt/nDeploy/scripts/init_unison.py - is not required on the slave!

You just need the unison binary

**Comment by sergeng** [comment]
DNS and hosts name resolution working OK!
[root@web-01 tasks]# cat /etc/hosts
127.0.0.1               localhost localhost.localdomain localhost4 localhost4.localdomain4
::1             localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.40.102          web-02.domain.name web-02
192.168.40.103          web-03.domain.name web-03
192.168.40.101          web-01.domain.name web-01

[root@web-01 tasks]# ping web-02.domain.name
PING web-02.domain.name (192.168.40.102) 56(84) bytes of data.
64 bytes from web-02.domain.name (192.168.40.102): icmp_seq=1 ttl=64 time=0.382 ms
64 bytes from web-02.domain.name (192.168.40.102): icmp_seq=2 ttl=64 time=0.691 ms
^C
--- web-02.domain.name ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.382/0.536/0.691/0.156 ms
[root@web-01 tasks]#

**Comment by sergeng** [comment]
Also SSH working without password prompt;
[root@web-01 tasks]# ssh root@web-02.domain.name
Last failed login: Sun Aug 28 14:59:55 JST 2016 from web-01.domain.name on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Sun Aug 28 13:45:44 2016 from 192.168.0.8
[root@web-02 ~]# 

**How to re-trigger the nDeploy_unison process?**

**Comment by AnoopAlias** [comment]
```
cat .unison/web-02.domain.name.prf 
# Unison preferences file
root = /home
root = ssh://root@web-02.domain.name:22//home

```


Unison works over SSH .Something is preventing it from doing so.So can run unison manually from the command line like

`unison web-02.domain.name`

and see whats going on

**Comment by sergeng** [comment]
OK initial sync working now!
[root@web-01 ~]# **unison /home ssh://web-02.domain.name//home**
Contacting server...
Connected [//web-01.domain.name//home -> //web-02.domain.name//home]
Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
        /home
        //web-02.domain.name//home
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted: 
http://www.cis.upenn.edu/~bcpierce/unison

\ account1/mail/new/1463417402.H171009P119739.cpanel.domain.com,S=86

**Comment by sergeng** [comment]
thank you again!

**Comment by AnoopAlias** [comment]
If you have lots of data..the initial sync can take a lot of time depending on your disk speed and network speed. View it like an rsync transfer and it will take almost similar time frame to sync

**Comment by sergeng** [comment]
unison Crash @ 15% ; 
Shortcut: copied /home/account1/public_html/install/ftp_search_will_look_for_this_file from local file /home/virtfs/.unison.account2.e454e04b4863bc21457890d3ed86a821.unison.tmp/tmp/yum-root-JC0D7l/epel-release-7-5.noarch.rpm
 15%  26:06 ETASegmentation fault (core dumped)
[root@web-01 ~]# unison -v
U

On slave the directory is;
/home/.unison.cpaccount01.e454e04b4863bc21457890d3ed86a821.unison.tmp
instead of
/home/cpaccount01

any hint?

**Comment by sergeng** [comment]
it seems that it's all boils down to this script
/opt/nDeploy/scripts/cluster_home_ensure_all.py

How to run it manually without this error;
`ERROR! Missing target hosts
^CTraceback (most recent call last):
  File "/opt/nDeploy/scripts/cluster_home_ensure_all.py", line 12, in <module>
    subprocess.call('/usr/bin/ansible -i /opt/nDeploy/conf/nDeploy-cluster/hosts -m user -a "name='+cpaneluser+' home='+cpaneluserhome+'"', shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 [ERROR]: User interrupted execution`

**Comment by sergeng** [comment]
OK found what was missing in **/opt/nDeploy/scripts/cluster_home_ensure_all.py** !
subprocess.call('ansible -i /opt/nDeploy/conf/nDeploy-cluster/hosts **ndeployslaves** -m user -a "name='+cpaneluser+' home='+cpaneluserhome+'"', shell=True)

**Comment by sergeng** [comment]
**manual sync works now!**
but why the unison process is **always exited**?
`[root@web-01 ~]# systemctl status ndeploy_unison
â— ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; enabled; vendor preset: disabled)
   Active: active (exited) since Sun 2016-08-28 14:59:55 JST; 22h ago
Aug 28 14:59:55 web-01.globaal.net systemd[1]: Starting nDeploy Unison...
Aug 28 14:59:55 web-01.globaal.net systemd[1]: Started nDeploy Unison.
Aug 28 16:43:56 web-01.globaal.net systemd[1]: Started nDeploy Unison.`

**Comment by AnoopAlias** [comment]
@sergeng - You need to check whats causing the segfault in unison. In my experience, if you omit certain temp/cache folders it would work just fine .

In unison preference file you can add 

`ignore = Path `


Refer unison manual for more info

**Comment by sergeng** [comment]
**I did this to debug;**
/usr/local/pythonz/pythons/CPython-3.5.2/bin/python -m pudb.run /opt/nDeploy/scripts/init_unison.py start

**then when I exited it was running;**
[root@web-01 ~]#   1%  00:04 ETAFailed [clamav]: No user clamav
  4%  00:01 ETAFailed [clamav]: No user clamav
100%  00:00 ETAFailed [clamav]: No user clamav

**So I checked the process and;**
[root@web-01 ~]# systemctl status ndeploy_unison
â— ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; enabled; vendor preset: disabled)
   Active: active (exited) since Sun 2016-08-28 14:59:55 JST; 1 day 19h ago

Aug 28 14:59:55 web-01.globaal.net systemd[1]: Starting nDeploy Unison...
Aug 28 14:59:55 web-01.globaal.net systemd[1]: Started nDeploy Unison.
Aug 28 16:43:56 web-01.globaal.net systemd[1]: Started nDeploy Unison.

[root@web-01 ~]# ps -aux |grep unison
root     28951  6.7  4.4 803044 726396 pts/0   S    10:48   0:26 /usr/bin/unison web-02.globaal.net
root     28952  6.8  4.4 802820 726176 pts/0   S    10:48   0:27 /usr/bin/unison web-03.globaal.net
root     28953  0.0  0.0  74548  3604 pts/0    S    10:48   0:00 ssh -l root -p 22 web-02.globaal.net -e none unison -server
root     28954  0.0  0.0  74548  3604 pts/0    S    10:48   0:00 ssh -l root -p 22 web-03.globaal.net -e none unison -server
root     30660  0.0  0.0 112652   972 pts/0    S+   10:55   0:00 grep --color=auto unison

Clearly it has something to do with the python binary version
**should I modify the script?** 
[root@web-01 ~]# cat /opt/nDeploy/scripts/init_unison.py           
#!/usr/bin/env python
or 
**change the default python env path?**

**Comment by AnoopAlias** [comment]
I just wrote the init script in python.

AFAIK unison is written in Ocaml and has nothing to do with python!

**Comment by sergeng** [comment]
I mean if it works with python full path
where should I change it to make the python script works without segfaulting?

**Comment by AnoopAlias** [comment]
It is not Python. It is ocaml 
 No use tampering with python . From the error you pasted it looks like a user account not created is causing issue
 Can you check in that direction

**Comment by sergeng** [comment]
**Starting ndeploy_unison with systemd errors:**
[root@web-01 ~]# systemctl stop ndeploy_unison
[root@web-01 ~]# systemctl start ndeploy_unison
[root@web-01 ~]# systemctl status ndeploy_unison
â— ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; enabled; vendor preset: disabled)
   **Active: active (exited)** since Sun 2016-09-04 13:47:59 JST; 4s ago
  Process: 9238 ExecStart=/opt/nDeploy/scripts/init_unison.py start (code=exited, status=0/SUCCESS)
 Main PID: 26148 (code=exited, status=0/SUCCESS)

Sep 04 13:47:58 web-01.globaal.net systemd[1]: Starting nDeploy Unison...
Sep 04 13:47:59 web-01.globaal.net systemd[1]: Started nDeploy Unison.
[root@web-01 ~]# journalctl _PID=26148
-- Logs begin at Sat 2016-09-03 16:12:14 JST, end at Sun 2016-09-04 13:48:19 JST. --
[root@web-01 ~]# 
[root@web-01 ~]# ps aux |grep unison
root      9305  0.0  0.0 112648   972 pts/0    S+   13:48   0:00 grep --color=auto unison

**Starting ndeploy_unison directly succeed:** 
[root@web-01 ~]# **/opt/nDeploy/scripts/init_unison.py start**
[root@web-01 ~]# ps aux |grep unison                      
root      9358 41.5  2.7 798056 446504 pts/0   R    13:49   0:00 /usr/bin/unison web-02.globaal.net
root      9359 36.0  2.7 797120 444928 pts/0   R    13:49   0:00 /usr/bin/unison web-03.globaal.net
root      9360  1.0  0.0  74548  3604 pts/0    S    13:49   0:00 ssh -l root -p 22 web-02.globaal.net -e none unison -server
root      9361  0.5  0.0  74548  3604 pts/0    S    13:49   0:00 ssh -l root -p 22 web-03.globaal.net -e none unison -server
root      9363  0.0  0.0 112648   972 pts/0    S+   13:49   0:00 grep --color=auto unison
[root@web-01 ~]#

any hints?

**Comment by AnoopAlias** [comment]
On a system we manage I dont see a problem in starting ndeploy_unison from systemd

```
 systemctl status ndeploy_unison
● ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-07-27 02:09:12 EDT; 1 months 8 days ago
 Main PID: 13458 (unison)
   CGroup: /system.slice/ndeploy_unison.service
           ├─13458 /usr/bin/unison centos6.sysally.net
           └─13459 ssh -l root -p 22 centos6.sysally.net -e none unison -server
```

Ensure that you have not tampered with the systemd unit file 

 https://raw.githubusercontent.com/AnoopAlias/nDeploy/master/rpm_buildtree/nDeploy-unison-pkg-centos7/usr/lib/systemd/system/ndeploy_unison.service

**Comment by sergeng** [comment]
running en Centos 7.2 EA4
used your posted system unit file above
same "exited" ERROR
**how to debug and verbose?**

**Comment by AnoopAlias** [comment]
I am not sure of what's wrong with your system. Does ndeploy_unison exit immediately on start or only after some time. 

This is another server which I installed yesterday 

```
# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

# systemctl status ndeploy_unison.service
● ndeploy_unison.service - nDeploy Unison
   Loaded: loaded (/usr/lib/systemd/system/ndeploy_unison.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-09-08 11:01:29 UTC; 1 day 1h ago
 Main PID: 3930 (unison)
   CGroup: /system.slice/ndeploy_unison.service
           ├─3930 /usr/bin/unison x.members.linode.com
           └─3931 ssh -l root -p 22 x.members.linode.com -e none unison -server

Sep 08 11:01:29 x.members.linode.com systemd[1]: Starting nDeploy Unison...
Sep 08 11:01:29 x.members.linode.com systemd[1]: Started nDeploy Unison.

```

Is your environment a container(openvz/lxc/virtuozzo) or something?


As far as log is concerned . systemd is just initiating a python script ( /opt/nDeploy/scripts/init_unison.py ) which in the end is calling the unison binary in daemon mode.

systemd and unison has logs .

The important thing to note is wheter unison is not starting at all or if its exiting after sometime (which I have noticed randomly sometime due to unison segfaulting ..)

**Comment by ghost** [comment]
why you say **I am not sure of what's wrong with your system**
it's your code, and it's your apps. are you copycat ?

this issue just remove temporary file on **.unison** folder

**Comment by AnoopAlias** [comment]
@mekbuk eh? .. I didn't get what you mean and what this has to do with an issue closed in 2017 :-1:

**Comment by ghost** [comment]
YOUR APPS IS SUCKS

**Comment by AnoopAlias** [comment]
@mekbuk - I am just trying to make a living and provide some value to the open source community which I respect. if you are simply here to make hate comments.I have nothing more to say to you.

**Comment by ghost** [comment]
you're nothing with bugs report? you know?
