### ISSUE TITLE
Slave php modules

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#95]
after clean install of nDeploy cluster install
we are missing those php modules on the slaves (php -m):
bz2
exif
fileinfo
gettext
iconv
ionCube Loader
zip

How to add them with this script /opt/nDeploy/scripts/easy_php_setup.sh ?

**Comment by AnoopAlias** [comment]
http://ndeploy.readthedocs.io/en/latest/PHP.html

See the section Additional PHP modules from ea-php repo/remi repo to add additional modules

you will need to install the modules from ea-php/remi repo on all the servers individually and restart
ndeploy_backends on all the servers.

**Comment by sergeng** [comment]
thank you.
Is apache available as backend for the slaves also?
does the apache config sync from the master to the slaves?

**Comment by AnoopAlias** [comment]
Httpd config is not synced. If you choose proxy as backend the slaves will just proxy to the master and the system will work like a CDN

**Comment by sergeng** [comment]
what do mean exactly?
"...and the system will work like a CDN"

**Comment by AnoopAlias** [comment]
if you select PROXY >> apache >> Proxy to cPanel httpd .. as the template for a domain The cluster will work and each of the slaves will be connecting to the upstream (master) server honouring any PROXY caching setup you have in the config .This is exactly how CDN's like CloudFlare works

**Comment by sergeng** [comment]
you mean the slaves will work solely as PROXY CACHE

**Comment by AnoopAlias** [comment]
PROXY or PROXY CACHE as per the template was chosen.
