### ISSUE TITLE
Varnish cache in front of NginX

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#96]
What is the supported way(that persist on update) to change nginx port ?
and the supported way to install varnish cache?

**Comment by AnoopAlias** [comment]
```
[root@cpanel conf]# pwd
/opt/nDeploy/conf
```
```
[root@cpanel conf]# ls server*
server_ssl_ocsp.tmpl  server_ssl.tmpl  server.tmpl
[root@cpanel conf]# 

```
Are the files you need to edit. Note that you will need to make the changes manually after nDeploy upgrade.

I would not recommend varnish as nginx is capable of doing caching and conditional cache purge with suitable rules . varnish is making the stack more complex

**Comment by sergeng** [comment]
ok thank you very much!
