### ISSUE TITLE
Redis Cache for Mysql

### ISSUE THREAD

**Issue by sergeng** [AnoopAlias/nDeploy#97]
Do you still recommend to install Redis as PHP backend as documented in the old nDeploy guide?
What will be the supported way to install Redis as in-memory cache for MariaDB Galera Cluster?

**Comment by AnoopAlias** [comment]
yes redis is recommended as a php session backend as it can be shared. I havent checked on redis as a MariaDB cache . Galera will not work in a typical cPanel setup. you need dedicated mysql or master-master replication

**Comment by sergeng** [comment]
**I have installed Galera cluster on the cpanel servers(no dedicated) and it is working really good!**
[root@web-01 ~]# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 27224
Server version: 10.1.16-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show status like 'wsrep%';
+------------------------------+----------------------------------------------------------------+
| Variable_name                | Value                                                          |
+------------------------------+----------------------------------------------------------------+
| wsrep_apply_oooe             | 0.000000                                                       |
| wsrep_apply_oool             | 0.000000                                                       |
| wsrep_apply_window           | 1.000000                                                       |
| wsrep_causal_reads           | 0                                                              |
| wsrep_cert_deps_distance     | 18.500572                                                      |
| wsrep_cert_index_size        | 48                                                             |
| wsrep_cert_interval          | 0.000000                                                       |
| wsrep_cluster_conf_id        | 39                                                             |
| wsrep_cluster_size           | 3                                                              |
| wsrep_cluster_state_uuid     | 45be9d57-68fb-11e6-b2a1-731700d33a7e                           |
| wsrep_cluster_status         | Primary                                                        |
| wsrep_commit_oooe            | 0.000000                                                       |
| wsrep_commit_oool            | 0.000000                                                       |
| wsrep_commit_window          | 1.000000                                                       |
| wsrep_connected              | ON                                                             |
| wsrep_evs_delayed            |                                                                |
| wsrep_evs_evict_list         |                                                                |
| wsrep_evs_repl_latency       | 0/0/0/0/0                                                      |
| wsrep_evs_state              | OPERATIONAL                                                    |
| wsrep_flow_control_paused    | 0.000000                                                       |
| wsrep_flow_control_paused_ns | 0                                                              |
| wsrep_flow_control_recv      | 0                                                              |
| wsrep_flow_control_sent      | 0                                                              |
| wsrep_gcomm_uuid             | bb4badd6-6c3a-11e6-be4a-93e38f9d1585                           |
| wsrep_incoming_addresses     | 192.168.40.102:13306,192.168.40.103:13306,192.168.40.101:13306 |
| wsrep_last_committed         | 100073                                                         |
| wsrep_local_bf_aborts        | 0                                                              |
| wsrep_local_cached_downto    | 96578                                                          |
| wsrep_local_cert_failures    | 0                                                              |
| wsrep_local_commits          | 3458                                                           |
| wsrep_local_index            | 2                                                              |
| wsrep_local_recv_queue       | 0                                                              |
| wsrep_local_recv_queue_avg   | 0.000000                                                       |
| wsrep_local_recv_queue_max   | 1                                                              |
| wsrep_local_recv_queue_min   | 0                                                              |
| wsrep_local_replays          | 0                                                              |
| wsrep_local_send_queue       | 0                                                              |
| wsrep_local_send_queue_avg   | 0.000000                                                       |
| wsrep_local_send_queue_max   | 1                                                              |
| wsrep_local_send_queue_min   | 0                                                              |
| wsrep_local_state            | 4                                                              |
| wsrep_local_state_comment    | Synced                                                         |
| wsrep_local_state_uuid       | 45be9d57-68fb-11e6-b2a1-731700d33a7e                           |
| wsrep_protocol_version       | 7                                                              |
| wsrep_provider_name          | Galera                                                         |
| wsrep_provider_vendor        | Codership Oy <info@codership.com>                              |
| wsrep_provider_version       | 25.3.15(r3578)                                                 |
| wsrep_ready                  | ON                                                             |
| wsrep_received               | 81                                                             |
| wsrep_received_bytes         | 959                                                            |
| wsrep_repl_data_bytes        | 1178441                                                        |
| wsrep_repl_keys              | 13809                                                          |
| wsrep_repl_keys_bytes        | 190880                                                         |
| wsrep_repl_other_bytes       | 0                                                              |
| wsrep_replicated             | 3496                                                           |
| wsrep_replicated_bytes       | 1593065                                                        |
| wsrep_thread_count           | 17                                                             |
+------------------------------+----------------------------------------------------------------+
57 rows in set (0.00 sec)

MariaDB [(none)]> 

**/etc/my.cnf Configuration to make it work!**
[galera]
# Mandatory settings
wsrep_on=ON
wsrep_provider=/usr/lib64/galera/libgalera_smm.so
wsrep_cluster_address="gcomm://192.168.40.101,192.168.40.102,192.168.40.103"
binlog_format=row
default_storage_engine=InnoDB
innodb_autoinc_lock_mode=2
#
# Allow server to accept connections on all interfaces.
#
bind-address=192.168.40.101
#
# Optional setting
wsrep_slave_threads=16
#innodb_flush_log_at_trx_commit=0

# cluster name
wsrep_cluster_name="WEB_Cluster"
# own IP address
wsrep_node_address="192.168.40.101"
wsrep_node_name="web-01.domain.name"
# replication provider
wsrep_sst_method=rsync

[client]
user=root
password=MyStrongPass@word

**Working inside WHM and cPanel too!**
Our requirement is to have the whole webstack in single node that can scale horizontally to unlimited nodes!!

**Comment by AnoopAlias** [comment]
But it doesnt sync mysql database right. The mysql db has user/pass for client databases . so it must be synced to all servers. mysql db is MyISAM only and it cannot be Innodb.

test a failover and see if the client access works.

**Comment by sergeng** [comment]
of course it sync the default MySQL db (MyISAM)!
[root@web-01 conf]# mysqlshow --count mysql
Database: mysql
+---------------------------+----------+------------+
|          Tables           | Columns  | Total Rows |
+---------------------------+----------+------------+
| column_stats              |       11 |          0 |
| columns_priv              |        7 |          0 |
| db                        |       22 |       1194 |
| event                     |       22 |          0 |
| func                      |        4 |          0 |
| general_log               |        6 |          0 |
| gtid_slave_pos            |        4 |          2 |
| help_category             |        4 |         40 |
| help_keyword              |        2 |        611 |
| help_relation             |        2 |       1218 |
| help_topic                |        6 |        583 |
| host                      |       20 |          0 |
| index_stats               |        5 |          0 |
| innodb_index_stats        |        8 |     108913 |
| innodb_table_stats        |        6 |      11615 |
| ndb_binlog_index          |       10 |          0 |
| plugin                    |        2 |          0 |
| proc                      |       20 |          0 |
| procs_priv                |        8 |          0 |
| proxies_priv              |        7 |          2 |
| roles_mapping             |        4 |          0 |
| servers                   |        9 |          0 |
| slave_master_info         |       23 |          0 |
| slave_relay_log_info      |        8 |          0 |
| slave_worker_info         |       12 |          0 |
| slow_log                  |       13 |          0 |
| table_stats               |        3 |          0 |
| tables_priv               |        8 |          0 |
| time_zone                 |        2 |          0 |
| time_zone_leap_second     |        2 |          0 |
| time_zone_name            |        2 |          0 |
| time_zone_transition      |        3 |          0 |
| time_zone_transition_type |        5 |          0 |
| user                      |       46 |        870 |
+---------------------------+----------+------------+
34 rows in set.

[root@web-02 ~]# mysqlshow --count mysql
Database: mysql
+---------------------------+----------+------------+
|          Tables           | Columns  | Total Rows |
+---------------------------+----------+------------+
| column_stats              |       11 |          0 |
| columns_priv              |        7 |          0 |
| db                        |       22 |       1242 |
| event                     |       22 |          0 |
| func                      |        4 |          0 |
| general_log               |        6 |          0 |
| gtid_slave_pos            |        4 |          2 |
| help_category             |        4 |         40 |
| help_keyword              |        2 |        611 |
| help_relation             |        2 |       1218 |
| help_topic                |        6 |        583 |
| host                      |       20 |          0 |
| index_stats               |        5 |          0 |
| innodb_index_stats        |        8 |     108913 |
| innodb_table_stats        |        6 |      11615 |
| ndb_binlog_index          |       10 |          0 |
| plugin                    |        2 |          0 |
| proc                      |       20 |          0 |
| procs_priv                |        8 |          0 |
| proxies_priv              |        7 |          2 |
| roles_mapping             |        4 |          0 |
| servers                   |        9 |          0 |
| slave_master_info         |       23 |          0 |
| slave_relay_log_info      |        8 |          0 |
| slave_worker_info         |       12 |          0 |
| slow_log                  |       13 |          0 |
| table_stats               |        3 |          0 |
| tables_priv               |        8 |          0 |
| time_zone                 |        2 |          0 |
| time_zone_leap_second     |        2 |          0 |
| time_zone_name            |        2 |          0 |
| time_zone_transition      |        3 |          0 |
| time_zone_transition_type |        5 |          0 |
| user                      |       46 |        870 |
+---------------------------+----------+------------+
34 rows in set.

[root@web-03 ~]# mysqlshow --count mysql
Database: mysql
+---------------------------+----------+------------+
|          Tables           | Columns  | Total Rows |
+---------------------------+----------+------------+
| column_stats              |       11 |          0 |
| columns_priv              |        7 |          0 |
| db                        |       22 |       1242 |
| event                     |       22 |          0 |
| func                      |        4 |          0 |
| general_log               |        6 |          0 |
| gtid_slave_pos            |        4 |          2 |
| help_category             |        4 |         40 |
| help_keyword              |        2 |        611 |
| help_relation             |        2 |       1218 |
| help_topic                |        6 |        583 |
| host                      |       20 |          0 |
| index_stats               |        5 |          0 |
| innodb_index_stats        |        8 |     108913 |
| innodb_table_stats        |        6 |      11615 |
| ndb_binlog_index          |       10 |          0 |
| plugin                    |        2 |          0 |
| proc                      |       20 |          0 |
| procs_priv                |        8 |          0 |
| proxies_priv              |        7 |          2 |
| roles_mapping             |        4 |          0 |
| servers                   |        9 |          0 |
| slave_master_info         |       23 |          0 |
| slave_relay_log_info      |        8 |          0 |
| slave_worker_info         |       12 |          0 |
| slow_log                  |       13 |          0 |
| table_stats               |        3 |          0 |
| tables_priv               |        8 |          0 |
| time_zone                 |        2 |          0 |
| time_zone_leap_second     |        2 |          0 |
| time_zone_name            |        2 |          0 |
| time_zone_transition      |        3 |          0 |
| time_zone_transition_type |        5 |          0 |
| user                      |       46 |        870 |
+---------------------------+----------+------------+
34 rows in set.

**Comment by AnoopAlias** [comment]
Ok I see http://galeracluster.com/documentation-webpages/userchanges.html.

Let me know how galera goes. Would be great if it could replace the master master stuff which is lot of problems.

**Comment by sergeng** [comment]
**TEST:1 MySQL Login from Any to Any**
[root@**web-01** ~]# mysql -h web-02 -P 13306
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 102
Server version: 10.1.16-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
[root@**web-01** ~]# mysql -h web-03 -P 13306 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 106
Server version: 10.1.16-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye

[root@**web-02** ~]# mysql -h web-01 -P 13306 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1784
Server version: 10.1.17-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
[root@**web-02** ~]# mysql -h web-03 -P 13306 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 127
Server version: 10.1.16-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye

[root@**web-03** ~]# mysql -h web-01 -P 13306
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1775
Server version: 10.1.17-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
[root@**web-03** ~]# mysql -h web-02 -P 13306 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 124
Server version: 10.1.16-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye

...To Be continued

**Comment by sergeng** [comment]
**TEST:2 Replication**
[root@**web-01** ~]# mysql -P 13306        
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1900
Server version: 10.1.17-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show status like 'wsrep%';
+------------------------------+----------------------------------------------------------------+
| Variable_name                | Value                                                          |
+------------------------------+----------------------------------------------------------------+
| wsrep_apply_oooe             | 0.000000                                                       |
| wsrep_apply_oool             | 0.000000                                                       |
| wsrep_apply_window           | 1.000000                                                       |
| wsrep_causal_reads           | 0                                                              |
| wsrep_cert_deps_distance     | 12.900415                                                      |
| wsrep_cert_index_size        | 39                                                             |
| wsrep_cert_interval          | 0.000000                                                       |
| wsrep_cluster_conf_id        | 7                                                              |
| **wsrep_cluster_size           | 3**                                                              |
| wsrep_cluster_state_uuid     | 45be9d57-68fb-11e6-b2a1-731700d33a7e                           |
| wsrep_cluster_status         | Primary                                                        |
| wsrep_commit_oooe            | 0.000000                                                       |
| wsrep_commit_oool            | 0.000000                                                       |
| wsrep_commit_window          | 1.000000                                                       |
| **wsrep_connected              | ON**                                                             |
| wsrep_desync_count           | 0                                                              |
| wsrep_evs_delayed            |                                                                |
| wsrep_evs_evict_list         |                                                                |
| wsrep_evs_repl_latency       | 0/0/0/0/0                                                      |
| wsrep_evs_state              | OPERATIONAL                                                    |
| wsrep_flow_control_paused    | 0.000000                                                       |
| wsrep_flow_control_paused_ns | 0                                                              |
| wsrep_flow_control_recv      | 0                                                              |
| wsrep_flow_control_sent      | 0                                                              |
| wsrep_gcomm_uuid             | e9d0a830-6f3a-11e6-9ade-82d4e44005fc                           |
| wsrep_incoming_addresses     | 192.168.40.102:13306,192.168.40.103:13306,192.168.40.101:13306 |
| wsrep_last_committed         | 101537                                                         |
| wsrep_local_bf_aborts        | 0                                                              |
| wsrep_local_cached_downto    | 101297                                                         |
| wsrep_local_cert_failures    | 0                                                              |
| wsrep_local_commits          | 241                                                            |
| wsrep_local_index            | 2                                                              |
| wsrep_local_recv_queue       | 0                                                              |
| wsrep_local_recv_queue_avg   | 0.055556                                                       |
| wsrep_local_recv_queue_max   | 2                                                              |
| wsrep_local_recv_queue_min   | 0                                                              |
| wsrep_local_replays          | 0                                                              |
| wsrep_local_send_queue       | 0                                                              |
| wsrep_local_send_queue_avg   | 0.000000                                                       |
| wsrep_local_send_queue_max   | 1                                                              |
| wsrep_local_send_queue_min   | 0                                                              |
| wsrep_local_state            | 4                                                              |
| **wsrep_local_state_comment    | Synced**                                                         |
| wsrep_local_state_uuid       | 45be9d57-68fb-11e6-b2a1-731700d33a7e                           |
| wsrep_protocol_version       | 7                                                              |
| wsrep_provider_name          | Galera                                                         |
| wsrep_provider_vendor        | Codership Oy <info@codership.com>                              |
| wsrep_provider_version       | 25.3.17(r3619)                                                 |
| wsrep_ready                  | ON                                                             |
| wsrep_received               | 18                                                             |
| wsrep_received_bytes         | 2006                                                           |
| wsrep_repl_data_bytes        | 59955                                                          |
| wsrep_repl_keys              | 964                                                            |
| wsrep_repl_keys_bytes        | 13255                                                          |
| wsrep_repl_other_bytes       | 0                                                              |
| wsrep_replicated             | 241                                                            |
| wsrep_replicated_bytes       | 88634                                                          |
| wsrep_thread_count           | 17                                                             |
+------------------------------+----------------------------------------------------------------+
58 rows in set (0.00 sec)

MariaDB [(none)]> **CREATE DATABASE galeratest;**
Query OK, 1 row affected (0.00 sec)

MariaDB [(none)]> USE galeratest;
Database changed
MariaDB [galeratest]> CREATE TABLE test_table (
    ->         id INT PRIMARY KEY AUTO_INCREMENT,
    ->         msg TEXT ) ENGINE=InnoDB;
Query OK, 0 rows affected (0.01 sec)

MariaDB [galeratest]> INSERT INTO test_table (msg)
    ->         VALUES ("Hello my dear cluster.");
Query OK, 1 row affected (0.00 sec)

MariaDB [galeratest]> INSERT INTO test_table (msg)
    ->         VALUES ("Hello, again, cluster dear.");
Query OK, 1 row affected (0.00 sec)


[root@**web-02** ~]# mysql -P 13306
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 125
Server version: 10.1.16-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> USE galeratest;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [galeratest]> SELECT * FROM test_table;
+----+-----------------------------+
| id | msg                         |
+----+-----------------------------+
|  3 | Hello my dear cluster.      |
|  6 | Hello, again, cluster dear. |
+----+-----------------------------+
2 rows in set (0.00 sec)


[root@**web-03** ~]# mysql -P 13306
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 128
Server version: 10.1.16-MariaDB MariaDB Server
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use galeratest;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [galeratest]> SELECT * FROM test_table;
+----+-----------------------------+
| id | msg                         |
+----+-----------------------------+
|  3 | Hello my dear cluster.      |
|  6 | Hello, again, cluster dear. |
+----+-----------------------------+
2 rows in set (0.00 sec)

**Comment by AnoopAlias** [comment]
Other downsides of Galera are that users cannnot have MyISAM tables + every tables should have a primary key

https://mariadb.com/kb/en/mariadb/mariadb-galera-cluster-known-limitations/
