### ISSUE TITLE
file download connection closed (Errror 206 code)

### ISSUE THREAD

**Issue by vacancy12345** [AnoopAlias/nDeploy#98]
Hello there

Fle download process by shutting down the nginx when the connection.

Error_log clean.

Wget screen

Saving to: ‘winzip200-32.msi.9’

`Saving to: ‘winzip200-32.msi.9’

 1% [>                                                                               ] 1,015,583    982KB/s   in 1.0s

2016-08-30 00:59:19 (982 KB/s) - Connection closed at byte 1015583. Retrying.
`

**Comment by AnoopAlias** [comment]
Check nginx error log and fix accordingly.
